#!/bin/bash
echo "=== Quick Debug Commands for VPS ==="
echo ""
echo "Run these on VPS to see the startup error:"
echo ""
echo "# 1. Check if Python is even starting:"
echo "docker-compose -f docker-compose.azure.yml exec backend python --version"
echo ""
echo "# 2. Try to import the app directly to see the error:"
echo "docker-compose -f docker-compose.azure.yml exec backend python -c 'from app.main import app'"
echo ""
echo "# 3. Check if there are any import errors:"
echo "docker-compose -f docker-compose.azure.yml exec backend python -c 'import app.services.verification_service'"
echo ""
echo "# 4. See ALL logs including stderr:"
echo "docker logs darshi-backend 2>&1"
echo ""
echo "# 5. Start backend manually to see error:"
echo "docker-compose -f docker-compose.azure.yml run --rm backend python -m app.main"
