-- Seed Data: Municipalities from Wikipedia
-- Generated by scripts/generate_muni_seed.py from 275 entries


INSERT INTO municipalities (id, name, state, district, population, website)
VALUES ('anantapur_mc', 'Anantapur Municipal Corporation', 'Andhra Pradesh', 'Anantapur', 262340, NULL)
ON CONFLICT (id) DO UPDATE SET
    name = EXCLUDED.name,
    state = EXCLUDED.state,
    district = EXCLUDED.district,
    population = EXCLUDED.population,
    website = EXCLUDED.website;

INSERT INTO municipalities (id, name, state, district, population, website)
VALUES ('chittoor_mc', 'Chittoor Municipal Corporation', 'Andhra Pradesh', 'Chittoor', 189000, NULL)
ON CONFLICT (id) DO UPDATE SET
    name = EXCLUDED.name,
    state = EXCLUDED.state,
    district = EXCLUDED.district,
    population = EXCLUDED.population,
    website = EXCLUDED.website;

INSERT INTO municipalities (id, name, state, district, population, website)
VALUES ('eluru_mc', 'Eluru Municipal Corporation', 'Andhra Pradesh', 'Eluru', 283648, NULL)
ON CONFLICT (id) DO UPDATE SET
    name = EXCLUDED.name,
    state = EXCLUDED.state,
    district = EXCLUDED.district,
    population = EXCLUDED.population,
    website = EXCLUDED.website;

INSERT INTO municipalities (id, name, state, district, population, website)
VALUES ('visakhapatnam_mc', 'Greater Visakhapatnam Municipal Corporation', 'Andhra Pradesh', 'Visakhapatnam & Anakapalli', 2035922, NULL)
ON CONFLICT (id) DO UPDATE SET
    name = EXCLUDED.name,
    state = EXCLUDED.state,
    district = EXCLUDED.district,
    population = EXCLUDED.population,
    website = EXCLUDED.website;

INSERT INTO municipalities (id, name, state, district, population, website)
VALUES ('guntur_mc', 'Guntur Municipal Corporation', 'Andhra Pradesh', 'Guntur', 743354, NULL)
ON CONFLICT (id) DO UPDATE SET
    name = EXCLUDED.name,
    state = EXCLUDED.state,
    district = EXCLUDED.district,
    population = EXCLUDED.population,
    website = EXCLUDED.website;

INSERT INTO municipalities (id, name, state, district, population, website)
VALUES ('kadapa_mc', 'Kadapa Municipal Corporation', 'Andhra Pradesh', 'YSR Kadapa', 341823, NULL)
ON CONFLICT (id) DO UPDATE SET
    name = EXCLUDED.name,
    state = EXCLUDED.state,
    district = EXCLUDED.district,
    population = EXCLUDED.population,
    website = EXCLUDED.website;

INSERT INTO municipalities (id, name, state, district, population, website)
VALUES ('kakinada_mc', 'Kakinada Municipal Corporation', 'Andhra Pradesh', 'Kakinada', 312255, NULL)
ON CONFLICT (id) DO UPDATE SET
    name = EXCLUDED.name,
    state = EXCLUDED.state,
    district = EXCLUDED.district,
    population = EXCLUDED.population,
    website = EXCLUDED.website;

INSERT INTO municipalities (id, name, state, district, population, website)
VALUES ('kurnool_mc', 'Kurnool Municipal Corporation', 'Andhra Pradesh', 'Kurnool', 460184, NULL)
ON CONFLICT (id) DO UPDATE SET
    name = EXCLUDED.name,
    state = EXCLUDED.state,
    district = EXCLUDED.district,
    population = EXCLUDED.population,
    website = EXCLUDED.website;

INSERT INTO municipalities (id, name, state, district, population, website)
VALUES ('machilipatnam_mc', 'Machilipatnam Municipal Corporation', 'Andhra Pradesh', 'Krishna', 189979, NULL)
ON CONFLICT (id) DO UPDATE SET
    name = EXCLUDED.name,
    state = EXCLUDED.state,
    district = EXCLUDED.district,
    population = EXCLUDED.population,
    website = EXCLUDED.website;

INSERT INTO municipalities (id, name, state, district, population, website)
VALUES ('mangalagiri_mc', 'Mangalagiri Tadepalli Municipal Corporation', 'Andhra Pradesh', 'Guntur', 320020, NULL)
ON CONFLICT (id) DO UPDATE SET
    name = EXCLUDED.name,
    state = EXCLUDED.state,
    district = EXCLUDED.district,
    population = EXCLUDED.population,
    website = EXCLUDED.website;

INSERT INTO municipalities (id, name, state, district, population, website)
VALUES ('nellore_mc', 'Nellore Municipal Corporation', 'Andhra Pradesh', 'SPS Nellore', 600869, NULL)
ON CONFLICT (id) DO UPDATE SET
    name = EXCLUDED.name,
    state = EXCLUDED.state,
    district = EXCLUDED.district,
    population = EXCLUDED.population,
    website = EXCLUDED.website;

INSERT INTO municipalities (id, name, state, district, population, website)
VALUES ('ongole_mc', 'Ongole Municipal Corporation', 'Andhra Pradesh', 'Prakasam', 252739, NULL)
ON CONFLICT (id) DO UPDATE SET
    name = EXCLUDED.name,
    state = EXCLUDED.state,
    district = EXCLUDED.district,
    population = EXCLUDED.population,
    website = EXCLUDED.website;

INSERT INTO municipalities (id, name, state, district, population, website)
VALUES ('rajamahendravaram_mc', 'Rajamahendravaram Municipal Corporation', 'Andhra Pradesh', 'East Godavari', 343903, NULL)
ON CONFLICT (id) DO UPDATE SET
    name = EXCLUDED.name,
    state = EXCLUDED.state,
    district = EXCLUDED.district,
    population = EXCLUDED.population,
    website = EXCLUDED.website;

INSERT INTO municipalities (id, name, state, district, population, website)
VALUES ('srikakulam_mc', 'Srikakulam Municipal Corporation', 'Andhra Pradesh', 'Srikakulam', 147936, NULL)
ON CONFLICT (id) DO UPDATE SET
    name = EXCLUDED.name,
    state = EXCLUDED.state,
    district = EXCLUDED.district,
    population = EXCLUDED.population,
    website = EXCLUDED.website;

INSERT INTO municipalities (id, name, state, district, population, website)
VALUES ('tirupati_mc', 'Tirupati Municipal Corporation', 'Andhra Pradesh', 'Tirupati', 287035, NULL)
ON CONFLICT (id) DO UPDATE SET
    name = EXCLUDED.name,
    state = EXCLUDED.state,
    district = EXCLUDED.district,
    population = EXCLUDED.population,
    website = EXCLUDED.website;

INSERT INTO municipalities (id, name, state, district, population, website)
VALUES ('vijayawada_mc', 'Vijayawada Municipal Corporation', 'Andhra Pradesh', 'NTR', 1448240, NULL)
ON CONFLICT (id) DO UPDATE SET
    name = EXCLUDED.name,
    state = EXCLUDED.state,
    district = EXCLUDED.district,
    population = EXCLUDED.population,
    website = EXCLUDED.website;

INSERT INTO municipalities (id, name, state, district, population, website)
VALUES ('vizianagaram_mc', 'Vizianagaram Municipal Corporation', 'Andhra Pradesh', 'Vizianagaram', 244598, NULL)
ON CONFLICT (id) DO UPDATE SET
    name = EXCLUDED.name,
    state = EXCLUDED.state,
    district = EXCLUDED.district,
    population = EXCLUDED.population,
    website = EXCLUDED.website;

INSERT INTO municipalities (id, name, state, district, population, website)
VALUES ('itanagar_mc', 'Itanagar Municipal Corporation', 'Arunachal Pradesh', 'Papum Pare', NULL, NULL)
ON CONFLICT (id) DO UPDATE SET
    name = EXCLUDED.name,
    state = EXCLUDED.state,
    district = EXCLUDED.district,
    population = EXCLUDED.population,
    website = EXCLUDED.website;

INSERT INTO municipalities (id, name, state, district, population, website)
VALUES ('guwahati_mc', 'Guwahati Municipal Corporation', 'Assam', 'Kamrup Metropolitan', 1260419, NULL)
ON CONFLICT (id) DO UPDATE SET
    name = EXCLUDED.name,
    state = EXCLUDED.state,
    district = EXCLUDED.district,
    population = EXCLUDED.population,
    website = EXCLUDED.website;

INSERT INTO municipalities (id, name, state, district, population, website)
VALUES ('dibrugarh_mc', 'Dibrugarh Municipal Corporation', 'Assam', 'Dibrugarh', 258000, NULL)
ON CONFLICT (id) DO UPDATE SET
    name = EXCLUDED.name,
    state = EXCLUDED.state,
    district = EXCLUDED.district,
    population = EXCLUDED.population,
    website = EXCLUDED.website;

INSERT INTO municipalities (id, name, state, district, population, website)
VALUES ('silchar_mc', 'Silchar Municipal Corporation', 'Assam', 'Cachar', 650000, NULL)
ON CONFLICT (id) DO UPDATE SET
    name = EXCLUDED.name,
    state = EXCLUDED.state,
    district = EXCLUDED.district,
    population = EXCLUDED.population,
    website = EXCLUDED.website;

INSERT INTO municipalities (id, name, state, district, population, website)
VALUES ('arrah_mc', 'Arrah Municipal Corporation', 'Bihar', 'Bhojpur', 461430, NULL)
ON CONFLICT (id) DO UPDATE SET
    name = EXCLUDED.name,
    state = EXCLUDED.state,
    district = EXCLUDED.district,
    population = EXCLUDED.population,
    website = EXCLUDED.website;

INSERT INTO municipalities (id, name, state, district, population, website)
VALUES ('begusarai_mc', 'Begusarai Municipal Corporation', 'Bihar', 'Begusarai', 252000, NULL)
ON CONFLICT (id) DO UPDATE SET
    name = EXCLUDED.name,
    state = EXCLUDED.state,
    district = EXCLUDED.district,
    population = EXCLUDED.population,
    website = EXCLUDED.website;

INSERT INTO municipalities (id, name, state, district, population, website)
VALUES ('bettiah_mc', 'Bettiah Municipal Corporation', 'Bihar', 'West Champaran', 156200, NULL)
ON CONFLICT (id) DO UPDATE SET
    name = EXCLUDED.name,
    state = EXCLUDED.state,
    district = EXCLUDED.district,
    population = EXCLUDED.population,
    website = EXCLUDED.website;

INSERT INTO municipalities (id, name, state, district, population, website)
VALUES ('bhagalpur_mc', 'Bhagalpur Municipal Corporation', 'Bihar', 'Bhagalpur', 410000, NULL)
ON CONFLICT (id) DO UPDATE SET
    name = EXCLUDED.name,
    state = EXCLUDED.state,
    district = EXCLUDED.district,
    population = EXCLUDED.population,
    website = EXCLUDED.website;

INSERT INTO municipalities (id, name, state, district, population, website)
VALUES ('bihar_sharif_mc', 'Bihar Sharif Municipal Corporation', 'Bihar', 'Nalanda', 296000, NULL)
ON CONFLICT (id) DO UPDATE SET
    name = EXCLUDED.name,
    state = EXCLUDED.state,
    district = EXCLUDED.district,
    population = EXCLUDED.population,
    website = EXCLUDED.website;

INSERT INTO municipalities (id, name, state, district, population, website)
VALUES ('chhapra_mc', 'Chhapra Municipal Corporation', 'Bihar', 'Saran', 249555, NULL)
ON CONFLICT (id) DO UPDATE SET
    name = EXCLUDED.name,
    state = EXCLUDED.state,
    district = EXCLUDED.district,
    population = EXCLUDED.population,
    website = EXCLUDED.website;

INSERT INTO municipalities (id, name, state, district, population, website)
VALUES ('darbhanga_mc', 'Darbhanga Municipal Corporation', 'Bihar', 'Darbhanga', 306612, NULL)
ON CONFLICT (id) DO UPDATE SET
    name = EXCLUDED.name,
    state = EXCLUDED.state,
    district = EXCLUDED.district,
    population = EXCLUDED.population,
    website = EXCLUDED.website;

INSERT INTO municipalities (id, name, state, district, population, website)
VALUES ('gaya_mc', 'Gaya Municipal Corporation', 'Bihar', 'Gaya', 560990, NULL)
ON CONFLICT (id) DO UPDATE SET
    name = EXCLUDED.name,
    state = EXCLUDED.state,
    district = EXCLUDED.district,
    population = EXCLUDED.population,
    website = EXCLUDED.website;

INSERT INTO municipalities (id, name, state, district, population, website)
VALUES ('katihar_mc', 'Katihar Municipal Corporation', 'Bihar', 'Katihar', 240565, NULL)
ON CONFLICT (id) DO UPDATE SET
    name = EXCLUDED.name,
    state = EXCLUDED.state,
    district = EXCLUDED.district,
    population = EXCLUDED.population,
    website = EXCLUDED.website;

INSERT INTO municipalities (id, name, state, district, population, website)
VALUES ('madhubani_india_mc', 'Madhubani Municipal Corporation', 'Bihar', 'Madhubani', 164156, NULL)
ON CONFLICT (id) DO UPDATE SET
    name = EXCLUDED.name,
    state = EXCLUDED.state,
    district = EXCLUDED.district,
    population = EXCLUDED.population,
    website = EXCLUDED.website;

INSERT INTO municipalities (id, name, state, district, population, website)
VALUES ('motihari_mc', 'Motihari Municipal Corporation', 'Bihar', 'East Champaran', 126158, NULL)
ON CONFLICT (id) DO UPDATE SET
    name = EXCLUDED.name,
    state = EXCLUDED.state,
    district = EXCLUDED.district,
    population = EXCLUDED.population,
    website = EXCLUDED.website;

INSERT INTO municipalities (id, name, state, district, population, website)
VALUES ('munger_mc', 'Munger Municipal Corporation', 'Bihar', 'Munger', 388000, NULL)
ON CONFLICT (id) DO UPDATE SET
    name = EXCLUDED.name,
    state = EXCLUDED.state,
    district = EXCLUDED.district,
    population = EXCLUDED.population,
    website = EXCLUDED.website;

INSERT INTO municipalities (id, name, state, district, population, website)
VALUES ('muzaffarpur_mc', 'Muzaffarpur Municipal Corporation', 'Bihar', 'Muzaffarpur', 393216, NULL)
ON CONFLICT (id) DO UPDATE SET
    name = EXCLUDED.name,
    state = EXCLUDED.state,
    district = EXCLUDED.district,
    population = EXCLUDED.population,
    website = EXCLUDED.website;

INSERT INTO municipalities (id, name, state, district, population, website)
VALUES ('patna_mc', 'Patna Municipal Corporation', 'Bihar', 'Patna', 2100216, NULL)
ON CONFLICT (id) DO UPDATE SET
    name = EXCLUDED.name,
    state = EXCLUDED.state,
    district = EXCLUDED.district,
    population = EXCLUDED.population,
    website = EXCLUDED.website;

INSERT INTO municipalities (id, name, state, district, population, website)
VALUES ('purnia_mc', 'Purnia Municipal Corporation', 'Bihar', 'Purnia', 510216, NULL)
ON CONFLICT (id) DO UPDATE SET
    name = EXCLUDED.name,
    state = EXCLUDED.state,
    district = EXCLUDED.district,
    population = EXCLUDED.population,
    website = EXCLUDED.website;

INSERT INTO municipalities (id, name, state, district, population, website)
VALUES ('saharsa_mc', 'Saharsa Municipal Corporation', 'Bihar', 'Saharsa', NULL, NULL)
ON CONFLICT (id) DO UPDATE SET
    name = EXCLUDED.name,
    state = EXCLUDED.state,
    district = EXCLUDED.district,
    population = EXCLUDED.population,
    website = EXCLUDED.website;

INSERT INTO municipalities (id, name, state, district, population, website)
VALUES ('samastipur_mc', 'Samastipur Municipal Corporation', 'Bihar', 'Samastipur', 256156, NULL)
ON CONFLICT (id) DO UPDATE SET
    name = EXCLUDED.name,
    state = EXCLUDED.state,
    district = EXCLUDED.district,
    population = EXCLUDED.population,
    website = EXCLUDED.website;

INSERT INTO municipalities (id, name, state, district, population, website)
VALUES ('sasaram_mc', 'Sasaram Municipal Corporation', 'Bihar', 'Rohtas', 310565, NULL)
ON CONFLICT (id) DO UPDATE SET
    name = EXCLUDED.name,
    state = EXCLUDED.state,
    district = EXCLUDED.district,
    population = EXCLUDED.population,
    website = EXCLUDED.website;

INSERT INTO municipalities (id, name, state, district, population, website)
VALUES ('sitamarhi_mc', 'Sitamarhi Municipal Corporation', 'Bihar', 'Sitamarhi', 150000, NULL)
ON CONFLICT (id) DO UPDATE SET
    name = EXCLUDED.name,
    state = EXCLUDED.state,
    district = EXCLUDED.district,
    population = EXCLUDED.population,
    website = EXCLUDED.website;

INSERT INTO municipalities (id, name, state, district, population, website)
VALUES ('ambikapur_mc', 'Ambikapur Municipal Corporation', 'Chhattisgarh', 'Surguja', 114575, NULL)
ON CONFLICT (id) DO UPDATE SET
    name = EXCLUDED.name,
    state = EXCLUDED.state,
    district = EXCLUDED.district,
    population = EXCLUDED.population,
    website = EXCLUDED.website;

INSERT INTO municipalities (id, name, state, district, population, website)
VALUES ('bhilai_charoda_mc', 'Bhilai Charoda Municipal Corporation', 'Chhattisgarh', 'Durg', 98008, NULL)
ON CONFLICT (id) DO UPDATE SET
    name = EXCLUDED.name,
    state = EXCLUDED.state,
    district = EXCLUDED.district,
    population = EXCLUDED.population,
    website = EXCLUDED.website;

INSERT INTO municipalities (id, name, state, district, population, website)
VALUES ('bhilai_mc', 'Bhilai Municipal Corporation', 'Chhattisgarh', 'Durg', 625697, NULL)
ON CONFLICT (id) DO UPDATE SET
    name = EXCLUDED.name,
    state = EXCLUDED.state,
    district = EXCLUDED.district,
    population = EXCLUDED.population,
    website = EXCLUDED.website;

INSERT INTO municipalities (id, name, state, district, population, website)
VALUES ('bilaspur_mc', 'Bilaspur Municipal Corporation', 'Chhattisgarh', 'Bilaspur', 689154, NULL)
ON CONFLICT (id) DO UPDATE SET
    name = EXCLUDED.name,
    state = EXCLUDED.state,
    district = EXCLUDED.district,
    population = EXCLUDED.population,
    website = EXCLUDED.website;

INSERT INTO municipalities (id, name, state, district, population, website)
VALUES ('birgaon_mc', 'Birgaon Municipal Corporation', 'Chhattisgarh', 'Raipur', 108491, NULL)
ON CONFLICT (id) DO UPDATE SET
    name = EXCLUDED.name,
    state = EXCLUDED.state,
    district = EXCLUDED.district,
    population = EXCLUDED.population,
    website = EXCLUDED.website;

INSERT INTO municipalities (id, name, state, district, population, website)
VALUES ('chirmiri_mc', 'Chirmiri Municipal Corporation', 'Chhattisgarh', 'Koriya', 101378, NULL)
ON CONFLICT (id) DO UPDATE SET
    name = EXCLUDED.name,
    state = EXCLUDED.state,
    district = EXCLUDED.district,
    population = EXCLUDED.population,
    website = EXCLUDED.website;

INSERT INTO municipalities (id, name, state, district, population, website)
VALUES ('dhamtari_mc', 'Dhamtari Municipal Corporation', 'Chhattisgarh', 'Dhamtari', 108500, NULL)
ON CONFLICT (id) DO UPDATE SET
    name = EXCLUDED.name,
    state = EXCLUDED.state,
    district = EXCLUDED.district,
    population = EXCLUDED.population,
    website = EXCLUDED.website;

INSERT INTO municipalities (id, name, state, district, population, website)
VALUES ('durg_mc', 'Durg Municipal Corporation', 'Chhattisgarh', 'Durg', 268679, NULL)
ON CONFLICT (id) DO UPDATE SET
    name = EXCLUDED.name,
    state = EXCLUDED.state,
    district = EXCLUDED.district,
    population = EXCLUDED.population,
    website = EXCLUDED.website;

INSERT INTO municipalities (id, name, state, district, population, website)
VALUES ('jagdalpur_mc', 'Jagdalpur Municipal Corporation', 'Chhattisgarh', 'Bastar', 325345, NULL)
ON CONFLICT (id) DO UPDATE SET
    name = EXCLUDED.name,
    state = EXCLUDED.state,
    district = EXCLUDED.district,
    population = EXCLUDED.population,
    website = EXCLUDED.website;

INSERT INTO municipalities (id, name, state, district, population, website)
VALUES ('korba_mc', 'Korba Municipal Corporation', 'Chhattisgarh', 'Korba', 263210, NULL)
ON CONFLICT (id) DO UPDATE SET
    name = EXCLUDED.name,
    state = EXCLUDED.state,
    district = EXCLUDED.district,
    population = EXCLUDED.population,
    website = EXCLUDED.website;

INSERT INTO municipalities (id, name, state, district, population, website)
VALUES ('raigarh_mc', 'Raigarh Municipal Corporation', 'Chhattisgarh', 'Raigarh', 137097, NULL)
ON CONFLICT (id) DO UPDATE SET
    name = EXCLUDED.name,
    state = EXCLUDED.state,
    district = EXCLUDED.district,
    population = EXCLUDED.population,
    website = EXCLUDED.website;

INSERT INTO municipalities (id, name, state, district, population, website)
VALUES ('raipur_mc', 'Raipur Municipal Corporation', 'Chhattisgarh', 'Raipur', 1010087, NULL)
ON CONFLICT (id) DO UPDATE SET
    name = EXCLUDED.name,
    state = EXCLUDED.state,
    district = EXCLUDED.district,
    population = EXCLUDED.population,
    website = EXCLUDED.website;

INSERT INTO municipalities (id, name, state, district, population, website)
VALUES ('rajnandgaon_mc', 'Rajnandgaon Municipal Corporation', 'Chhattisgarh', 'Rajnandgaon', 163122, NULL)
ON CONFLICT (id) DO UPDATE SET
    name = EXCLUDED.name,
    state = EXCLUDED.state,
    district = EXCLUDED.district,
    population = EXCLUDED.population,
    website = EXCLUDED.website;

INSERT INTO municipalities (id, name, state, district, population, website)
VALUES ('risali_mc', 'Risali Municipal Corporation', 'Chhattisgarh', 'Durg', 105000, NULL)
ON CONFLICT (id) DO UPDATE SET
    name = EXCLUDED.name,
    state = EXCLUDED.state,
    district = EXCLUDED.district,
    population = EXCLUDED.population,
    website = EXCLUDED.website;

INSERT INTO municipalities (id, name, state, district, population, website)
VALUES ('panaji_mc', 'Panaji City Corporation', 'Goa', 'North Goa', 40000, NULL)
ON CONFLICT (id) DO UPDATE SET
    name = EXCLUDED.name,
    state = EXCLUDED.state,
    district = EXCLUDED.district,
    population = EXCLUDED.population,
    website = EXCLUDED.website;

INSERT INTO municipalities (id, name, state, district, population, website)
VALUES ('ahmedabad_mc', 'Ahmedabad Municipal Corporation', 'Gujarat', 'Ahmedabad', 8253455, NULL)
ON CONFLICT (id) DO UPDATE SET
    name = EXCLUDED.name,
    state = EXCLUDED.state,
    district = EXCLUDED.district,
    population = EXCLUDED.population,
    website = EXCLUDED.website;

INSERT INTO municipalities (id, name, state, district, population, website)
VALUES ('surat_mc', 'Surat Municipal Corporation', 'Gujarat', 'Surat', 7490598, NULL)
ON CONFLICT (id) DO UPDATE SET
    name = EXCLUDED.name,
    state = EXCLUDED.state,
    district = EXCLUDED.district,
    population = EXCLUDED.population,
    website = EXCLUDED.website;

INSERT INTO municipalities (id, name, state, district, population, website)
VALUES ('gandhinagar_mc', 'Gandhinagar Municipal Corporation', 'Gujarat', 'Gandhinagar', 410618, NULL)
ON CONFLICT (id) DO UPDATE SET
    name = EXCLUDED.name,
    state = EXCLUDED.state,
    district = EXCLUDED.district,
    population = EXCLUDED.population,
    website = EXCLUDED.website;

INSERT INTO municipalities (id, name, state, district, population, website)
VALUES ('vadodara_mc', 'Vadodara Municipal Corporation', 'Gujarat', 'Vadodara', 3522221, NULL)
ON CONFLICT (id) DO UPDATE SET
    name = EXCLUDED.name,
    state = EXCLUDED.state,
    district = EXCLUDED.district,
    population = EXCLUDED.population,
    website = EXCLUDED.website;

INSERT INTO municipalities (id, name, state, district, population, website)
VALUES ('rajkot_mc', 'Rajkot Municipal Corporation', 'Gujarat', 'Rajkot', 1934975, NULL)
ON CONFLICT (id) DO UPDATE SET
    name = EXCLUDED.name,
    state = EXCLUDED.state,
    district = EXCLUDED.district,
    population = EXCLUDED.population,
    website = EXCLUDED.website;

INSERT INTO municipalities (id, name, state, district, population, website)
VALUES ('bhavnagar_mc', 'Bhavnagar Municipal Corporation', 'Gujarat', 'Bhavnagar', 771365, NULL)
ON CONFLICT (id) DO UPDATE SET
    name = EXCLUDED.name,
    state = EXCLUDED.state,
    district = EXCLUDED.district,
    population = EXCLUDED.population,
    website = EXCLUDED.website;

INSERT INTO municipalities (id, name, state, district, population, website)
VALUES ('jamnagar_mc', 'Jamnagar Municipal Corporation', 'Gujarat', 'Jamnagar', 682302, NULL)
ON CONFLICT (id) DO UPDATE SET
    name = EXCLUDED.name,
    state = EXCLUDED.state,
    district = EXCLUDED.district,
    population = EXCLUDED.population,
    website = EXCLUDED.website;

INSERT INTO municipalities (id, name, state, district, population, website)
VALUES ('junagadh_mc', 'Junagadh Municipal Corporation', 'Gujarat', 'Junagadh', 415838, NULL)
ON CONFLICT (id) DO UPDATE SET
    name = EXCLUDED.name,
    state = EXCLUDED.state,
    district = EXCLUDED.district,
    population = EXCLUDED.population,
    website = EXCLUDED.website;

INSERT INTO municipalities (id, name, state, district, population, website)
VALUES ('anand_mc', 'Karamsad Anand Municipal Corporation', 'Gujarat', 'Anand', 412106, NULL)
ON CONFLICT (id) DO UPDATE SET
    name = EXCLUDED.name,
    state = EXCLUDED.state,
    district = EXCLUDED.district,
    population = EXCLUDED.population,
    website = EXCLUDED.website;

INSERT INTO municipalities (id, name, state, district, population, website)
VALUES ('nadiad_mc', 'Nadiad Municipal Corporation', 'Gujarat', 'Kheda', 385979, NULL)
ON CONFLICT (id) DO UPDATE SET
    name = EXCLUDED.name,
    state = EXCLUDED.state,
    district = EXCLUDED.district,
    population = EXCLUDED.population,
    website = EXCLUDED.website;

INSERT INTO municipalities (id, name, state, district, population, website)
VALUES ('mehsana_mc', 'Mehsana Municipal Corporation', 'Gujarat', 'Mehsana', 320000, NULL)
ON CONFLICT (id) DO UPDATE SET
    name = EXCLUDED.name,
    state = EXCLUDED.state,
    district = EXCLUDED.district,
    population = EXCLUDED.population,
    website = EXCLUDED.website;

INSERT INTO municipalities (id, name, state, district, population, website)
VALUES ('navsari_mc', 'Navsari Municipal Corporation', 'Gujarat', 'Navsari', 367000, NULL)
ON CONFLICT (id) DO UPDATE SET
    name = EXCLUDED.name,
    state = EXCLUDED.state,
    district = EXCLUDED.district,
    population = EXCLUDED.population,
    website = EXCLUDED.website;

INSERT INTO municipalities (id, name, state, district, population, website)
VALUES ('surendranagar_mc', 'Surendranagar Municipal Corporation', 'Gujarat', 'Surendranagar', 329000, NULL)
ON CONFLICT (id) DO UPDATE SET
    name = EXCLUDED.name,
    state = EXCLUDED.state,
    district = EXCLUDED.district,
    population = EXCLUDED.population,
    website = EXCLUDED.website;

INSERT INTO municipalities (id, name, state, district, population, website)
VALUES ('morbi_mc', 'Morbi Municipal Corporation', 'Gujarat', 'Morbi', 327000, NULL)
ON CONFLICT (id) DO UPDATE SET
    name = EXCLUDED.name,
    state = EXCLUDED.state,
    district = EXCLUDED.district,
    population = EXCLUDED.population,
    website = EXCLUDED.website;

INSERT INTO municipalities (id, name, state, district, population, website)
VALUES ('gandhidham_mc', 'Gandhidham Municipal Corporation', 'Gujarat', 'Kutch', 322000, NULL)
ON CONFLICT (id) DO UPDATE SET
    name = EXCLUDED.name,
    state = EXCLUDED.state,
    district = EXCLUDED.district,
    population = EXCLUDED.population,
    website = EXCLUDED.website;

INSERT INTO municipalities (id, name, state, district, population, website)
VALUES ('porbandar_mc', 'Porbandar - Chhaya Municipal Corporation', 'Gujarat', 'Porbandar', 300000, NULL)
ON CONFLICT (id) DO UPDATE SET
    name = EXCLUDED.name,
    state = EXCLUDED.state,
    district = EXCLUDED.district,
    population = EXCLUDED.population,
    website = EXCLUDED.website;

INSERT INTO municipalities (id, name, state, district, population, website)
VALUES ('vapi_mc', 'Vapi Municipal Corporation', 'Gujarat', 'Valsad', 350000, NULL)
ON CONFLICT (id) DO UPDATE SET
    name = EXCLUDED.name,
    state = EXCLUDED.state,
    district = EXCLUDED.district,
    population = EXCLUDED.population,
    website = EXCLUDED.website;

INSERT INTO municipalities (id, name, state, district, population, website)
VALUES ('gurugram_mc', 'Gurugram Municipal Corporation', 'Haryana', 'Gurugram', 876969, NULL)
ON CONFLICT (id) DO UPDATE SET
    name = EXCLUDED.name,
    state = EXCLUDED.state,
    district = EXCLUDED.district,
    population = EXCLUDED.population,
    website = EXCLUDED.website;

INSERT INTO municipalities (id, name, state, district, population, website)
VALUES ('faridabad_mc', 'Faridabad Municipal Corporation', 'Haryana', 'Faridabad', 1400000, NULL)
ON CONFLICT (id) DO UPDATE SET
    name = EXCLUDED.name,
    state = EXCLUDED.state,
    district = EXCLUDED.district,
    population = EXCLUDED.population,
    website = EXCLUDED.website;

INSERT INTO municipalities (id, name, state, district, population, website)
VALUES ('sonipat_mc', 'Sonipat Municipal Corporation', 'Haryana', 'Sonipat', 596974, NULL)
ON CONFLICT (id) DO UPDATE SET
    name = EXCLUDED.name,
    state = EXCLUDED.state,
    district = EXCLUDED.district,
    population = EXCLUDED.population,
    website = EXCLUDED.website;

INSERT INTO municipalities (id, name, state, district, population, website)
VALUES ('panchkula_mc', 'Panchkula Municipal Corporation', 'Haryana', 'Panchkula', 558890, NULL)
ON CONFLICT (id) DO UPDATE SET
    name = EXCLUDED.name,
    state = EXCLUDED.state,
    district = EXCLUDED.district,
    population = EXCLUDED.population,
    website = EXCLUDED.website;

INSERT INTO municipalities (id, name, state, district, population, website)
VALUES ('yamunanagar_mc', 'Yamunanagar Municipal Corporation', 'Haryana', 'Yamunanagar', 532000, NULL)
ON CONFLICT (id) DO UPDATE SET
    name = EXCLUDED.name,
    state = EXCLUDED.state,
    district = EXCLUDED.district,
    population = EXCLUDED.population,
    website = EXCLUDED.website;

INSERT INTO municipalities (id, name, state, district, population, website)
VALUES ('rohtak_mc', 'Rohtak Municipal Corporation', 'Haryana', 'Rohtak', 373133, NULL)
ON CONFLICT (id) DO UPDATE SET
    name = EXCLUDED.name,
    state = EXCLUDED.state,
    district = EXCLUDED.district,
    population = EXCLUDED.population,
    website = EXCLUDED.website;

INSERT INTO municipalities (id, name, state, district, population, website)
VALUES ('karnal_mc', 'Karnal Municipal Corporation', 'Haryana', 'Karnal', 310989, NULL)
ON CONFLICT (id) DO UPDATE SET
    name = EXCLUDED.name,
    state = EXCLUDED.state,
    district = EXCLUDED.district,
    population = EXCLUDED.population,
    website = EXCLUDED.website;

INSERT INTO municipalities (id, name, state, district, population, website)
VALUES ('hisar_mc', 'Hisar Municipal Corporation', 'Haryana', 'Hisar', 301249, NULL)
ON CONFLICT (id) DO UPDATE SET
    name = EXCLUDED.name,
    state = EXCLUDED.state,
    district = EXCLUDED.district,
    population = EXCLUDED.population,
    website = EXCLUDED.website;

INSERT INTO municipalities (id, name, state, district, population, website)
VALUES ('panipat_mc', 'Panipat Municipal Corporation', 'Haryana', 'Panipat', 294150, NULL)
ON CONFLICT (id) DO UPDATE SET
    name = EXCLUDED.name,
    state = EXCLUDED.state,
    district = EXCLUDED.district,
    population = EXCLUDED.population,
    website = EXCLUDED.website;

INSERT INTO municipalities (id, name, state, district, population, website)
VALUES ('ambala_mc', 'Ambala Municipal Corporation', 'Haryana', 'Ambala', 128350, NULL)
ON CONFLICT (id) DO UPDATE SET
    name = EXCLUDED.name,
    state = EXCLUDED.state,
    district = EXCLUDED.district,
    population = EXCLUDED.population,
    website = EXCLUDED.website;

INSERT INTO municipalities (id, name, state, district, population, website)
VALUES ('manesar_mc', 'Manesar Municipal Corporation', 'Haryana', 'Gurgaon', 128350, NULL)
ON CONFLICT (id) DO UPDATE SET
    name = EXCLUDED.name,
    state = EXCLUDED.state,
    district = EXCLUDED.district,
    population = EXCLUDED.population,
    website = EXCLUDED.website;

INSERT INTO municipalities (id, name, state, district, population, website)
VALUES ('dharamshala_mc', 'Dharamshala Municipal Corporation', 'Himachal Pradesh', 'Kangra', 58260, NULL)
ON CONFLICT (id) DO UPDATE SET
    name = EXCLUDED.name,
    state = EXCLUDED.state,
    district = EXCLUDED.district,
    population = EXCLUDED.population,
    website = EXCLUDED.website;

INSERT INTO municipalities (id, name, state, district, population, website)
VALUES ('mandi_mc', 'Mandi Municipal Corporation', 'Himachal Pradesh', 'Mandi', 26422, NULL)
ON CONFLICT (id) DO UPDATE SET
    name = EXCLUDED.name,
    state = EXCLUDED.state,
    district = EXCLUDED.district,
    population = EXCLUDED.population,
    website = EXCLUDED.website;

INSERT INTO municipalities (id, name, state, district, population, website)
VALUES ('palampur_mc', 'Palampur Municipal Corporation', 'Himachal Pradesh', 'Kangra', 40385, NULL)
ON CONFLICT (id) DO UPDATE SET
    name = EXCLUDED.name,
    state = EXCLUDED.state,
    district = EXCLUDED.district,
    population = EXCLUDED.population,
    website = EXCLUDED.website;

INSERT INTO municipalities (id, name, state, district, population, website)
VALUES ('shimla_mc', 'Shimla Municipal Corporation', 'Himachal Pradesh', 'Shimla', 171817, NULL)
ON CONFLICT (id) DO UPDATE SET
    name = EXCLUDED.name,
    state = EXCLUDED.state,
    district = EXCLUDED.district,
    population = EXCLUDED.population,
    website = EXCLUDED.website;

INSERT INTO municipalities (id, name, state, district, population, website)
VALUES ('solan_mc', 'Solan Municipal Corporation', 'Himachal Pradesh', 'Solan', 35280, NULL)
ON CONFLICT (id) DO UPDATE SET
    name = EXCLUDED.name,
    state = EXCLUDED.state,
    district = EXCLUDED.district,
    population = EXCLUDED.population,
    website = EXCLUDED.website;

INSERT INTO municipalities (id, name, state, district, population, website)
VALUES ('adityapur_mc', 'Adityapur Municipal Corporation', 'Jharkhand', 'Seraikela Kharsawan', 225628, NULL)
ON CONFLICT (id) DO UPDATE SET
    name = EXCLUDED.name,
    state = EXCLUDED.state,
    district = EXCLUDED.district,
    population = EXCLUDED.population,
    website = EXCLUDED.website;

INSERT INTO municipalities (id, name, state, district, population, website)
VALUES ('chas_mc', 'Chas Municipal Corporation', 'Jharkhand', 'Bokaro', 563417, NULL)
ON CONFLICT (id) DO UPDATE SET
    name = EXCLUDED.name,
    state = EXCLUDED.state,
    district = EXCLUDED.district,
    population = EXCLUDED.population,
    website = EXCLUDED.website;

INSERT INTO municipalities (id, name, state, district, population, website)
VALUES ('deoghar_mc', 'Deoghar Municipal Corporation', 'Jharkhand', 'Deoghar', 283116, NULL)
ON CONFLICT (id) DO UPDATE SET
    name = EXCLUDED.name,
    state = EXCLUDED.state,
    district = EXCLUDED.district,
    population = EXCLUDED.population,
    website = EXCLUDED.website;

INSERT INTO municipalities (id, name, state, district, population, website)
VALUES ('dhanbad_mc', 'Dhanbad Municipal Corporation', 'Jharkhand', 'Dhanbad', 1195298, NULL)
ON CONFLICT (id) DO UPDATE SET
    name = EXCLUDED.name,
    state = EXCLUDED.state,
    district = EXCLUDED.district,
    population = EXCLUDED.population,
    website = EXCLUDED.website;

INSERT INTO municipalities (id, name, state, district, population, website)
VALUES ('giridih_mc', 'Giridih Municipal Corporation', 'Jharkhand', 'Giridih', 143529, NULL)
ON CONFLICT (id) DO UPDATE SET
    name = EXCLUDED.name,
    state = EXCLUDED.state,
    district = EXCLUDED.district,
    population = EXCLUDED.population,
    website = EXCLUDED.website;

INSERT INTO municipalities (id, name, state, district, population, website)
VALUES ('hazaribagh_mc', 'Hazaribagh Municipal Corporation', 'Jharkhand', 'Hazaribagh', 186139, NULL)
ON CONFLICT (id) DO UPDATE SET
    name = EXCLUDED.name,
    state = EXCLUDED.state,
    district = EXCLUDED.district,
    population = EXCLUDED.population,
    website = EXCLUDED.website;

INSERT INTO municipalities (id, name, state, district, population, website)
VALUES ('jamshedpur_mc', 'Mango Municipal Corporation', 'Jharkhand', 'East Singhbhum', 224002, NULL)
ON CONFLICT (id) DO UPDATE SET
    name = EXCLUDED.name,
    state = EXCLUDED.state,
    district = EXCLUDED.district,
    population = EXCLUDED.population,
    website = EXCLUDED.website;

INSERT INTO municipalities (id, name, state, district, population, website)
VALUES ('medininagar_mc', 'Medininagar Municipal Corporation', 'Jharkhand', 'Palamu', 158941, NULL)
ON CONFLICT (id) DO UPDATE SET
    name = EXCLUDED.name,
    state = EXCLUDED.state,
    district = EXCLUDED.district,
    population = EXCLUDED.population,
    website = EXCLUDED.website;

INSERT INTO municipalities (id, name, state, district, population, website)
VALUES ('ranchi_mc', 'Ranchi Municipal Corporation', 'Jharkhand', 'Ranchi', 1126741, NULL)
ON CONFLICT (id) DO UPDATE SET
    name = EXCLUDED.name,
    state = EXCLUDED.state,
    district = EXCLUDED.district,
    population = EXCLUDED.population,
    website = EXCLUDED.website;

INSERT INTO municipalities (id, name, state, district, population, website)
VALUES ('city_mc', 'Corporation Name in English', 'Karnataka', 'District(s)', NULL, NULL)
ON CONFLICT (id) DO UPDATE SET
    name = EXCLUDED.name,
    state = EXCLUDED.state,
    district = EXCLUDED.district,
    population = EXCLUDED.population,
    website = EXCLUDED.website;

INSERT INTO municipalities (id, name, state, district, population, website)
VALUES ('ballari_mc', 'Ballari City Corporation', 'Karnataka', 'Ballari', 409444, NULL)
ON CONFLICT (id) DO UPDATE SET
    name = EXCLUDED.name,
    state = EXCLUDED.state,
    district = EXCLUDED.district,
    population = EXCLUDED.population,
    website = EXCLUDED.website;

INSERT INTO municipalities (id, name, state, district, population, website)
VALUES ('belagavi_mc', 'Belagavi City Corporation', 'Karnataka', 'Belagavi', 490045, NULL)
ON CONFLICT (id) DO UPDATE SET
    name = EXCLUDED.name,
    state = EXCLUDED.state,
    district = EXCLUDED.district,
    population = EXCLUDED.population,
    website = EXCLUDED.website;

INSERT INTO municipalities (id, name, state, district, population, website)
VALUES ('bengaluru_mc', 'Bengaluru Central City Corporation', 'Karnataka', 'Bangalore Urban', 8443675, NULL)
ON CONFLICT (id) DO UPDATE SET
    name = EXCLUDED.name,
    state = EXCLUDED.state,
    district = EXCLUDED.district,
    population = EXCLUDED.population,
    website = EXCLUDED.website;

INSERT INTO municipalities (id, name, state, district, population, website)
VALUES ('168_mc', 'Bengaluru East City Corporation', 'Karnataka', '50', NULL, NULL)
ON CONFLICT (id) DO UPDATE SET
    name = EXCLUDED.name,
    state = EXCLUDED.state,
    district = EXCLUDED.district,
    population = EXCLUDED.population,
    website = EXCLUDED.website;

INSERT INTO municipalities (id, name, state, district, population, website)
VALUES ('158_mc', 'Bengaluru North City Corporation', 'Karnataka', '72', NULL, NULL)
ON CONFLICT (id) DO UPDATE SET
    name = EXCLUDED.name,
    state = EXCLUDED.state,
    district = EXCLUDED.district,
    population = EXCLUDED.population,
    website = EXCLUDED.website;

INSERT INTO municipalities (id, name, state, district, population, website)
VALUES ('147_mc', 'Bengaluru South City Corporation', 'Karnataka', '72', NULL, NULL)
ON CONFLICT (id) DO UPDATE SET
    name = EXCLUDED.name,
    state = EXCLUDED.state,
    district = EXCLUDED.district,
    population = EXCLUDED.population,
    website = EXCLUDED.website;

INSERT INTO municipalities (id, name, state, district, population, website)
VALUES ('161_mc', 'Bengaluru West City Corporation', 'Karnataka', '111', NULL, NULL)
ON CONFLICT (id) DO UPDATE SET
    name = EXCLUDED.name,
    state = EXCLUDED.state,
    district = EXCLUDED.district,
    population = EXCLUDED.population,
    website = EXCLUDED.website;

INSERT INTO municipalities (id, name, state, district, population, website)
VALUES ('bidar_mc', 'Bidar City Corporation', 'Karnataka', 'Bidar', 201620, NULL)
ON CONFLICT (id) DO UPDATE SET
    name = EXCLUDED.name,
    state = EXCLUDED.state,
    district = EXCLUDED.district,
    population = EXCLUDED.population,
    website = EXCLUDED.website;

INSERT INTO municipalities (id, name, state, district, population, website)
VALUES ('davanagere_mc', 'Davanagere City Corporation', 'Karnataka', 'Davanagere', 435128, NULL)
ON CONFLICT (id) DO UPDATE SET
    name = EXCLUDED.name,
    state = EXCLUDED.state,
    district = EXCLUDED.district,
    population = EXCLUDED.population,
    website = EXCLUDED.website;

INSERT INTO municipalities (id, name, state, district, population, website)
VALUES ('dharwad_mc', 'Dharwad City Corporation', 'Karnataka', 'Dharwad', 943857, NULL)
ON CONFLICT (id) DO UPDATE SET
    name = EXCLUDED.name,
    state = EXCLUDED.state,
    district = EXCLUDED.district,
    population = EXCLUDED.population,
    website = EXCLUDED.website;

INSERT INTO municipalities (id, name, state, district, population, website)
VALUES ('hassan_mc', 'Hassan City Corporation', 'Karnataka', 'Hassan', 155006, NULL)
ON CONFLICT (id) DO UPDATE SET
    name = EXCLUDED.name,
    state = EXCLUDED.state,
    district = EXCLUDED.district,
    population = EXCLUDED.population,
    website = EXCLUDED.website;

INSERT INTO municipalities (id, name, state, district, population, website)
VALUES ('hubli_mc', 'Hubballi City Corporation', 'Karnataka', 'Dharwad', 943857, NULL)
ON CONFLICT (id) DO UPDATE SET
    name = EXCLUDED.name,
    state = EXCLUDED.state,
    district = EXCLUDED.district,
    population = EXCLUDED.population,
    website = EXCLUDED.website;

INSERT INTO municipalities (id, name, state, district, population, website)
VALUES ('kalaburagi_mc', 'Kalaburagi City Corporation', 'Karnataka', 'Kalaburagi', 533587, NULL)
ON CONFLICT (id) DO UPDATE SET
    name = EXCLUDED.name,
    state = EXCLUDED.state,
    district = EXCLUDED.district,
    population = EXCLUDED.population,
    website = EXCLUDED.website;

INSERT INTO municipalities (id, name, state, district, population, website)
VALUES ('mangaluru_mc', 'Mangaluru City Corporation', 'Karnataka', 'Dakshina Kannada', 724159, NULL)
ON CONFLICT (id) DO UPDATE SET
    name = EXCLUDED.name,
    state = EXCLUDED.state,
    district = EXCLUDED.district,
    population = EXCLUDED.population,
    website = EXCLUDED.website;

INSERT INTO municipalities (id, name, state, district, population, website)
VALUES ('mysuru_mc', 'Mysuru City Corporation', 'Karnataka', 'Mysuru', 920550, NULL)
ON CONFLICT (id) DO UPDATE SET
    name = EXCLUDED.name,
    state = EXCLUDED.state,
    district = EXCLUDED.district,
    population = EXCLUDED.population,
    website = EXCLUDED.website;

INSERT INTO municipalities (id, name, state, district, population, website)
VALUES ('raichur_mc', 'Raichur City Corporation', 'Karnataka', 'Raichur', 234073, NULL)
ON CONFLICT (id) DO UPDATE SET
    name = EXCLUDED.name,
    state = EXCLUDED.state,
    district = EXCLUDED.district,
    population = EXCLUDED.population,
    website = EXCLUDED.website;

INSERT INTO municipalities (id, name, state, district, population, website)
VALUES ('shivamogga_mc', 'Shivamogga City Corporation', 'Karnataka', 'Shivamogga', 322650, NULL)
ON CONFLICT (id) DO UPDATE SET
    name = EXCLUDED.name,
    state = EXCLUDED.state,
    district = EXCLUDED.district,
    population = EXCLUDED.population,
    website = EXCLUDED.website;

INSERT INTO municipalities (id, name, state, district, population, website)
VALUES ('tumkur_mc', 'Tumakuru City Corporation', 'Karnataka', 'Tumakuru', 305821, NULL)
ON CONFLICT (id) DO UPDATE SET
    name = EXCLUDED.name,
    state = EXCLUDED.state,
    district = EXCLUDED.district,
    population = EXCLUDED.population,
    website = EXCLUDED.website;

INSERT INTO municipalities (id, name, state, district, population, website)
VALUES ('vijayapura_mc', 'Vijayapura City Corporation', 'Karnataka', 'Vijayapura', 326360, NULL)
ON CONFLICT (id) DO UPDATE SET
    name = EXCLUDED.name,
    state = EXCLUDED.state,
    district = EXCLUDED.district,
    population = EXCLUDED.population,
    website = EXCLUDED.website;

INSERT INTO municipalities (id, name, state, district, population, website)
VALUES ('thiruvananthapuram_mc', 'Thiruvananthapuram Municipal Corporation', 'Kerala', 'Thiruvananthapuram', 957730, NULL)
ON CONFLICT (id) DO UPDATE SET
    name = EXCLUDED.name,
    state = EXCLUDED.state,
    district = EXCLUDED.district,
    population = EXCLUDED.population,
    website = EXCLUDED.website;

INSERT INTO municipalities (id, name, state, district, population, website)
VALUES ('kozhikode_mc', 'Kozhikode Municipal Corporation', 'Kerala', 'Kozhikode', 609214, NULL)
ON CONFLICT (id) DO UPDATE SET
    name = EXCLUDED.name,
    state = EXCLUDED.state,
    district = EXCLUDED.district,
    population = EXCLUDED.population,
    website = EXCLUDED.website;

INSERT INTO municipalities (id, name, state, district, population, website)
VALUES ('kochi_mc', 'Kochi Municipal Corporation', 'Kerala', 'Ernakulam', 601574, NULL)
ON CONFLICT (id) DO UPDATE SET
    name = EXCLUDED.name,
    state = EXCLUDED.state,
    district = EXCLUDED.district,
    population = EXCLUDED.population,
    website = EXCLUDED.website;

INSERT INTO municipalities (id, name, state, district, population, website)
VALUES ('kollam_mc', 'Kollam Municipal Corporation', 'Kerala', 'Kollam', 388288, NULL)
ON CONFLICT (id) DO UPDATE SET
    name = EXCLUDED.name,
    state = EXCLUDED.state,
    district = EXCLUDED.district,
    population = EXCLUDED.population,
    website = EXCLUDED.website;

INSERT INTO municipalities (id, name, state, district, population, website)
VALUES ('thrissur_mc', 'Thrissur Municipal Corporation', 'Kerala', 'Thrissur', 315596, NULL)
ON CONFLICT (id) DO UPDATE SET
    name = EXCLUDED.name,
    state = EXCLUDED.state,
    district = EXCLUDED.district,
    population = EXCLUDED.population,
    website = EXCLUDED.website;

INSERT INTO municipalities (id, name, state, district, population, website)
VALUES ('kannur_mc', 'Kannur Municipal Corporation', 'Kerala', 'Kannur', 232486, NULL)
ON CONFLICT (id) DO UPDATE SET
    name = EXCLUDED.name,
    state = EXCLUDED.state,
    district = EXCLUDED.district,
    population = EXCLUDED.population,
    website = EXCLUDED.website;

INSERT INTO municipalities (id, name, state, district, population, website)
VALUES ('bhopal_mc', 'Bhopal Municipal Corporation', 'Madhya Pradesh', 'Bhopal', 1886100, NULL)
ON CONFLICT (id) DO UPDATE SET
    name = EXCLUDED.name,
    state = EXCLUDED.state,
    district = EXCLUDED.district,
    population = EXCLUDED.population,
    website = EXCLUDED.website;

INSERT INTO municipalities (id, name, state, district, population, website)
VALUES ('burhanpur_mc', 'Burhanpur Municipal Corporation', 'Madhya Pradesh', 'Burhanpur', 300892, NULL)
ON CONFLICT (id) DO UPDATE SET
    name = EXCLUDED.name,
    state = EXCLUDED.state,
    district = EXCLUDED.district,
    population = EXCLUDED.population,
    website = EXCLUDED.website;

INSERT INTO municipalities (id, name, state, district, population, website)
VALUES ('chhindwara_mc', 'Chhindwara Municipal Corporation', 'Madhya Pradesh', 'Chhindwara', 234784, NULL)
ON CONFLICT (id) DO UPDATE SET
    name = EXCLUDED.name,
    state = EXCLUDED.state,
    district = EXCLUDED.district,
    population = EXCLUDED.population,
    website = EXCLUDED.website;

INSERT INTO municipalities (id, name, state, district, population, website)
VALUES ('dewas_mc', 'Dewas Municipal Corporation', 'Madhya Pradesh', 'Dewas', 289438, NULL)
ON CONFLICT (id) DO UPDATE SET
    name = EXCLUDED.name,
    state = EXCLUDED.state,
    district = EXCLUDED.district,
    population = EXCLUDED.population,
    website = EXCLUDED.website;

INSERT INTO municipalities (id, name, state, district, population, website)
VALUES ('gwalior_mc', 'Gwalior Municipal Corporation', 'Madhya Pradesh', 'Gwalior', 1117740, NULL)
ON CONFLICT (id) DO UPDATE SET
    name = EXCLUDED.name,
    state = EXCLUDED.state,
    district = EXCLUDED.district,
    population = EXCLUDED.population,
    website = EXCLUDED.website;

INSERT INTO municipalities (id, name, state, district, population, website)
VALUES ('indore_mc', 'Indore Municipal Corporation', 'Madhya Pradesh', 'Indore', 2167447, NULL)
ON CONFLICT (id) DO UPDATE SET
    name = EXCLUDED.name,
    state = EXCLUDED.state,
    district = EXCLUDED.district,
    population = EXCLUDED.population,
    website = EXCLUDED.website;

INSERT INTO municipalities (id, name, state, district, population, website)
VALUES ('jabalpur_mc', 'Jabalpur Municipal Corporation', 'Madhya Pradesh', 'Jabalpur', 1268848, NULL)
ON CONFLICT (id) DO UPDATE SET
    name = EXCLUDED.name,
    state = EXCLUDED.state,
    district = EXCLUDED.district,
    population = EXCLUDED.population,
    website = EXCLUDED.website;

INSERT INTO municipalities (id, name, state, district, population, website)
VALUES ('katni_mc', 'Katni Municipal Corporation', 'Madhya Pradesh', 'Katni', 221875, NULL)
ON CONFLICT (id) DO UPDATE SET
    name = EXCLUDED.name,
    state = EXCLUDED.state,
    district = EXCLUDED.district,
    population = EXCLUDED.population,
    website = EXCLUDED.website;

INSERT INTO municipalities (id, name, state, district, population, website)
VALUES ('khandwa_mc', 'Khandwa Municipal Corporation', 'Madhya Pradesh', 'Khandwa', 259436, NULL)
ON CONFLICT (id) DO UPDATE SET
    name = EXCLUDED.name,
    state = EXCLUDED.state,
    district = EXCLUDED.district,
    population = EXCLUDED.population,
    website = EXCLUDED.website;

INSERT INTO municipalities (id, name, state, district, population, website)
VALUES ('morena_mc', 'Morena Municipal Corporation', 'Madhya Pradesh', 'Morena', 218768, NULL)
ON CONFLICT (id) DO UPDATE SET
    name = EXCLUDED.name,
    state = EXCLUDED.state,
    district = EXCLUDED.district,
    population = EXCLUDED.population,
    website = EXCLUDED.website;

INSERT INTO municipalities (id, name, state, district, population, website)
VALUES ('ratlam_mc', 'Ratlam Municipal Corporation', 'Madhya Pradesh', 'Ratlam', 273892, NULL)
ON CONFLICT (id) DO UPDATE SET
    name = EXCLUDED.name,
    state = EXCLUDED.state,
    district = EXCLUDED.district,
    population = EXCLUDED.population,
    website = EXCLUDED.website;

INSERT INTO municipalities (id, name, state, district, population, website)
VALUES ('rewa_mc', 'Rewa Municipal Corporation', 'Madhya Pradesh', 'Rewa', 235422, NULL)
ON CONFLICT (id) DO UPDATE SET
    name = EXCLUDED.name,
    state = EXCLUDED.state,
    district = EXCLUDED.district,
    population = EXCLUDED.population,
    website = EXCLUDED.website;

INSERT INTO municipalities (id, name, state, district, population, website)
VALUES ('sagar_mc', 'Sagar Municipal Corporation', 'Madhya Pradesh', 'Sagar', 370296, NULL)
ON CONFLICT (id) DO UPDATE SET
    name = EXCLUDED.name,
    state = EXCLUDED.state,
    district = EXCLUDED.district,
    population = EXCLUDED.population,
    website = EXCLUDED.website;

INSERT INTO municipalities (id, name, state, district, population, website)
VALUES ('satna_mc', 'Satna Municipal Corporation', 'Madhya Pradesh', 'Satna', 283004, NULL)
ON CONFLICT (id) DO UPDATE SET
    name = EXCLUDED.name,
    state = EXCLUDED.state,
    district = EXCLUDED.district,
    population = EXCLUDED.population,
    website = EXCLUDED.website;

INSERT INTO municipalities (id, name, state, district, population, website)
VALUES ('singrauli_mc', 'Singrauli Municipal Corporation', 'Madhya Pradesh', 'Singrauli', 225676, NULL)
ON CONFLICT (id) DO UPDATE SET
    name = EXCLUDED.name,
    state = EXCLUDED.state,
    district = EXCLUDED.district,
    population = EXCLUDED.population,
    website = EXCLUDED.website;

INSERT INTO municipalities (id, name, state, district, population, website)
VALUES ('ujjain_mc', 'Ujjain Municipal Corporation', 'Madhya Pradesh', 'Ujjain', 515215, NULL)
ON CONFLICT (id) DO UPDATE SET
    name = EXCLUDED.name,
    state = EXCLUDED.state,
    district = EXCLUDED.district,
    population = EXCLUDED.population,
    website = EXCLUDED.website;

INSERT INTO municipalities (id, name, state, district, population, website)
VALUES ('mumbai_mc', 'Brihanmumbai Municipal Corporation', 'Maharashtra', 'Mumbai City & Mumbai Suburban', 12442373, NULL)
ON CONFLICT (id) DO UPDATE SET
    name = EXCLUDED.name,
    state = EXCLUDED.state,
    district = EXCLUDED.district,
    population = EXCLUDED.population,
    website = EXCLUDED.website;

INSERT INTO municipalities (id, name, state, district, population, website)
VALUES ('pune_mc', 'Pune Municipal Corporation', 'Maharashtra', 'Pune', 6451618, NULL)
ON CONFLICT (id) DO UPDATE SET
    name = EXCLUDED.name,
    state = EXCLUDED.state,
    district = EXCLUDED.district,
    population = EXCLUDED.population,
    website = EXCLUDED.website;

INSERT INTO municipalities (id, name, state, district, population, website)
VALUES ('nagpur_mc', 'Nagpur Municipal Corporation', 'Maharashtra', 'Nagpur', 3428897, NULL)
ON CONFLICT (id) DO UPDATE SET
    name = EXCLUDED.name,
    state = EXCLUDED.state,
    district = EXCLUDED.district,
    population = EXCLUDED.population,
    website = EXCLUDED.website;

INSERT INTO municipalities (id, name, state, district, population, website)
VALUES ('nashik_mc', 'Nashik Municipal Corporation', 'Maharashtra', 'Nashik', 1886973, NULL)
ON CONFLICT (id) DO UPDATE SET
    name = EXCLUDED.name,
    state = EXCLUDED.state,
    district = EXCLUDED.district,
    population = EXCLUDED.population,
    website = EXCLUDED.website;

INSERT INTO municipalities (id, name, state, district, population, website)
VALUES ('thane_mc', 'Thane Municipal Corporation', 'Maharashtra', 'Thane', 1818872, NULL)
ON CONFLICT (id) DO UPDATE SET
    name = EXCLUDED.name,
    state = EXCLUDED.state,
    district = EXCLUDED.district,
    population = EXCLUDED.population,
    website = EXCLUDED.website;

INSERT INTO municipalities (id, name, state, district, population, website)
VALUES ('pimprichinchwad_mc', 'Pimpri Chinchwad Municipal Corporation', 'Maharashtra', 'Pune', 1729320, NULL)
ON CONFLICT (id) DO UPDATE SET
    name = EXCLUDED.name,
    state = EXCLUDED.state,
    district = EXCLUDED.district,
    population = EXCLUDED.population,
    website = EXCLUDED.website;

INSERT INTO municipalities (id, name, state, district, population, website)
VALUES ('kalyandombivli_mc', 'Kalyan-Dombivli Municipal Corporation', 'Maharashtra', 'Thane', 1246381, NULL)
ON CONFLICT (id) DO UPDATE SET
    name = EXCLUDED.name,
    state = EXCLUDED.state,
    district = EXCLUDED.district,
    population = EXCLUDED.population,
    website = EXCLUDED.website;

INSERT INTO municipalities (id, name, state, district, population, website)
VALUES ('vasaivirar_mc', 'Vasai-Virar City Municipal Corporation', 'Maharashtra', 'Palghar', 1221233, NULL)
ON CONFLICT (id) DO UPDATE SET
    name = EXCLUDED.name,
    state = EXCLUDED.state,
    district = EXCLUDED.district,
    population = EXCLUDED.population,
    website = EXCLUDED.website;

INSERT INTO municipalities (id, name, state, district, population, website)
VALUES ('chhatrapati_sambhajingar_mc', 'Chhatrapati Sambhajingar Municipal Corporation', 'Maharashtra', 'Chhatrapati Sambhajingar', 1171330, NULL)
ON CONFLICT (id) DO UPDATE SET
    name = EXCLUDED.name,
    state = EXCLUDED.state,
    district = EXCLUDED.district,
    population = EXCLUDED.population,
    website = EXCLUDED.website;

INSERT INTO municipalities (id, name, state, district, population, website)
VALUES ('navi_mumbai_mc', 'Navi Mumbai Municipal Corporation', 'Maharashtra', 'Thane', 1119477, NULL)
ON CONFLICT (id) DO UPDATE SET
    name = EXCLUDED.name,
    state = EXCLUDED.state,
    district = EXCLUDED.district,
    population = EXCLUDED.population,
    website = EXCLUDED.website;

INSERT INTO municipalities (id, name, state, district, population, website)
VALUES ('solapur_mc', 'Solapur Municipal Corporation', 'Maharashtra', 'Solapur', 951118, NULL)
ON CONFLICT (id) DO UPDATE SET
    name = EXCLUDED.name,
    state = EXCLUDED.state,
    district = EXCLUDED.district,
    population = EXCLUDED.population,
    website = EXCLUDED.website;

INSERT INTO municipalities (id, name, state, district, population, website)
VALUES ('mirabhayandar_mc', 'Mira-Bhayandar Municipal Corporation', 'Maharashtra', 'Thane', 814655, NULL)
ON CONFLICT (id) DO UPDATE SET
    name = EXCLUDED.name,
    state = EXCLUDED.state,
    district = EXCLUDED.district,
    population = EXCLUDED.population,
    website = EXCLUDED.website;

INSERT INTO municipalities (id, name, state, district, population, website)
VALUES ('bhiwandinizampur_mc', 'Bhiwandi-Nizampur Municipal Corporation', 'Maharashtra', 'Thane', 711329, NULL)
ON CONFLICT (id) DO UPDATE SET
    name = EXCLUDED.name,
    state = EXCLUDED.state,
    district = EXCLUDED.district,
    population = EXCLUDED.population,
    website = EXCLUDED.website;

INSERT INTO municipalities (id, name, state, district, population, website)
VALUES ('amravati_mc', 'Amravati Municipal Corporation', 'Maharashtra', 'Amravati', 646801, NULL)
ON CONFLICT (id) DO UPDATE SET
    name = EXCLUDED.name,
    state = EXCLUDED.state,
    district = EXCLUDED.district,
    population = EXCLUDED.population,
    website = EXCLUDED.website;

INSERT INTO municipalities (id, name, state, district, population, website)
VALUES ('nanded_mc', 'Nanded-Waghala Municipal Corporation', 'Maharashtra', 'Nanded', 550564, NULL)
ON CONFLICT (id) DO UPDATE SET
    name = EXCLUDED.name,
    state = EXCLUDED.state,
    district = EXCLUDED.district,
    population = EXCLUDED.population,
    website = EXCLUDED.website;

INSERT INTO municipalities (id, name, state, district, population, website)
VALUES ('kolhapur_mc', 'Kolhapur Municipal Corporation', 'Maharashtra', 'Kolhapur', 549236, NULL)
ON CONFLICT (id) DO UPDATE SET
    name = EXCLUDED.name,
    state = EXCLUDED.state,
    district = EXCLUDED.district,
    population = EXCLUDED.population,
    website = EXCLUDED.website;

INSERT INTO municipalities (id, name, state, district, population, website)
VALUES ('akola_mc', 'Akola Municipal Corporation', 'Maharashtra', 'Akola', 537489, 'https://amcakola.in')
ON CONFLICT (id) DO UPDATE SET
    name = EXCLUDED.name,
    state = EXCLUDED.state,
    district = EXCLUDED.district,
    population = EXCLUDED.population,
    website = EXCLUDED.website;

INSERT INTO municipalities (id, name, state, district, population, website)
VALUES ('panvel_mc', 'Panvel Municipal Corporation', 'Maharashtra', 'Raigad', 509901, NULL)
ON CONFLICT (id) DO UPDATE SET
    name = EXCLUDED.name,
    state = EXCLUDED.state,
    district = EXCLUDED.district,
    population = EXCLUDED.population,
    website = EXCLUDED.website;

INSERT INTO municipalities (id, name, state, district, population, website)
VALUES ('ulhasnagar_mc', 'Ulhasnagar Municipal Corporation', 'Maharashtra', 'Thane', 506937, NULL)
ON CONFLICT (id) DO UPDATE SET
    name = EXCLUDED.name,
    state = EXCLUDED.state,
    district = EXCLUDED.district,
    population = EXCLUDED.population,
    website = EXCLUDED.website;

INSERT INTO municipalities (id, name, state, district, population, website)
VALUES ('sanglimiraj__kupwad_mc', 'Sangali-Miraj-Kupwad Municipal Corporation', 'Maharashtra', 'Sangli', 502697, NULL)
ON CONFLICT (id) DO UPDATE SET
    name = EXCLUDED.name,
    state = EXCLUDED.state,
    district = EXCLUDED.district,
    population = EXCLUDED.population,
    website = EXCLUDED.website;

INSERT INTO municipalities (id, name, state, district, population, website)
VALUES ('malegaon_mc', 'Malegaon Municipal Corporation', 'Maharashtra', 'Nashik', 471006, NULL)
ON CONFLICT (id) DO UPDATE SET
    name = EXCLUDED.name,
    state = EXCLUDED.state,
    district = EXCLUDED.district,
    population = EXCLUDED.population,
    website = EXCLUDED.website;

INSERT INTO municipalities (id, name, state, district, population, website)
VALUES ('jalgaon_mc', 'Jalgaon Municipal Corporation', 'Maharashtra', 'Jalgaon', 460468, NULL)
ON CONFLICT (id) DO UPDATE SET
    name = EXCLUDED.name,
    state = EXCLUDED.state,
    district = EXCLUDED.district,
    population = EXCLUDED.population,
    website = EXCLUDED.website;

INSERT INTO municipalities (id, name, state, district, population, website)
VALUES ('latur_mc', 'Latur Municipal Corporation', 'Maharashtra', 'Latur', 382754, NULL)
ON CONFLICT (id) DO UPDATE SET
    name = EXCLUDED.name,
    state = EXCLUDED.state,
    district = EXCLUDED.district,
    population = EXCLUDED.population,
    website = EXCLUDED.website;

INSERT INTO municipalities (id, name, state, district, population, website)
VALUES ('dhule_mc', 'Dhule Municipal Corporation', 'Maharashtra', 'Dhule', 376093, NULL)
ON CONFLICT (id) DO UPDATE SET
    name = EXCLUDED.name,
    state = EXCLUDED.state,
    district = EXCLUDED.district,
    population = EXCLUDED.population,
    website = EXCLUDED.website;

INSERT INTO municipalities (id, name, state, district, population, website)
VALUES ('ahmednagar_mc', 'Ahmednagar Municipal Corporation', 'Maharashtra', 'Ahmednagar', 350905, NULL)
ON CONFLICT (id) DO UPDATE SET
    name = EXCLUDED.name,
    state = EXCLUDED.state,
    district = EXCLUDED.district,
    population = EXCLUDED.population,
    website = EXCLUDED.website;

INSERT INTO municipalities (id, name, state, district, population, website)
VALUES ('chandrapur_mc', 'Chandrapur Municipal Corporation', 'Maharashtra', 'Chandrapur', 321036, NULL)
ON CONFLICT (id) DO UPDATE SET
    name = EXCLUDED.name,
    state = EXCLUDED.state,
    district = EXCLUDED.district,
    population = EXCLUDED.population,
    website = EXCLUDED.website;

INSERT INTO municipalities (id, name, state, district, population, website)
VALUES ('parbhani_mc', 'Parbhani Municipal Corporation', 'Maharashtra', 'Parbhani', 307191, NULL)
ON CONFLICT (id) DO UPDATE SET
    name = EXCLUDED.name,
    state = EXCLUDED.state,
    district = EXCLUDED.district,
    population = EXCLUDED.population,
    website = EXCLUDED.website;

INSERT INTO municipalities (id, name, state, district, population, website)
VALUES ('ichalkaranji_mc', 'Ichalkaranji Municipal Corporation', 'Maharashtra', 'Kolhapur', 287570, NULL)
ON CONFLICT (id) DO UPDATE SET
    name = EXCLUDED.name,
    state = EXCLUDED.state,
    district = EXCLUDED.district,
    population = EXCLUDED.population,
    website = EXCLUDED.website;

INSERT INTO municipalities (id, name, state, district, population, website)
VALUES ('jalna_mc', 'Jalna Municipal Corporation', 'Maharashtra', 'Jalna', 285577, NULL)
ON CONFLICT (id) DO UPDATE SET
    name = EXCLUDED.name,
    state = EXCLUDED.state,
    district = EXCLUDED.district,
    population = EXCLUDED.population,
    website = EXCLUDED.website;

INSERT INTO municipalities (id, name, state, district, population, website)
VALUES ('imphal_mc', 'Imphal Municipal Corporation', 'Manipur', 'Imphal East & Imphal West', 250234, NULL)
ON CONFLICT (id) DO UPDATE SET
    name = EXCLUDED.name,
    state = EXCLUDED.state,
    district = EXCLUDED.district,
    population = EXCLUDED.population,
    website = EXCLUDED.website;

INSERT INTO municipalities (id, name, state, district, population, website)
VALUES ('aizawl_mc', 'Aizawl Municipal Corporation', 'Mizoram', 'Aizawl', 293416, NULL)
ON CONFLICT (id) DO UPDATE SET
    name = EXCLUDED.name,
    state = EXCLUDED.state,
    district = EXCLUDED.district,
    population = EXCLUDED.population,
    website = EXCLUDED.website;

INSERT INTO municipalities (id, name, state, district, population, website)
VALUES ('berhampur_mc', 'Berhampur Municipal Corporation', 'Odisha', 'Ganjam', 356598, NULL)
ON CONFLICT (id) DO UPDATE SET
    name = EXCLUDED.name,
    state = EXCLUDED.state,
    district = EXCLUDED.district,
    population = EXCLUDED.population,
    website = EXCLUDED.website;

INSERT INTO municipalities (id, name, state, district, population, website)
VALUES ('bhubaneswar_mc', 'Bhubaneswar Municipal Corporation', 'Odisha', 'Khordha', 837737, NULL)
ON CONFLICT (id) DO UPDATE SET
    name = EXCLUDED.name,
    state = EXCLUDED.state,
    district = EXCLUDED.district,
    population = EXCLUDED.population,
    website = EXCLUDED.website;

INSERT INTO municipalities (id, name, state, district, population, website)
VALUES ('cuttack_mc', 'Cuttack Municipal Corporation', 'Odisha', 'Cuttack', 650000, NULL)
ON CONFLICT (id) DO UPDATE SET
    name = EXCLUDED.name,
    state = EXCLUDED.state,
    district = EXCLUDED.district,
    population = EXCLUDED.population,
    website = EXCLUDED.website;

INSERT INTO municipalities (id, name, state, district, population, website)
VALUES ('rourkela_mc', 'Rourkela Municipal Corporation', 'Odisha', 'Sundergarh', 536450, NULL)
ON CONFLICT (id) DO UPDATE SET
    name = EXCLUDED.name,
    state = EXCLUDED.state,
    district = EXCLUDED.district,
    population = EXCLUDED.population,
    website = EXCLUDED.website;

INSERT INTO municipalities (id, name, state, district, population, website)
VALUES ('sambalpur_mc', 'Sambalpur Municipal Corporation', 'Odisha', 'Sambalpur', 335761, NULL)
ON CONFLICT (id) DO UPDATE SET
    name = EXCLUDED.name,
    state = EXCLUDED.state,
    district = EXCLUDED.district,
    population = EXCLUDED.population,
    website = EXCLUDED.website;

INSERT INTO municipalities (id, name, state, district, population, website)
VALUES ('puri_mc', 'Puri Municipal Corporation', 'Odisha', 'Puri', NULL, NULL)
ON CONFLICT (id) DO UPDATE SET
    name = EXCLUDED.name,
    state = EXCLUDED.state,
    district = EXCLUDED.district,
    population = EXCLUDED.population,
    website = EXCLUDED.website;

INSERT INTO municipalities (id, name, state, district, population, website)
VALUES ('ludhiana_mc', 'Ludhiana Municipal Corporation', 'Punjab', 'Ludhiana', 1613878, NULL)
ON CONFLICT (id) DO UPDATE SET
    name = EXCLUDED.name,
    state = EXCLUDED.state,
    district = EXCLUDED.district,
    population = EXCLUDED.population,
    website = EXCLUDED.website;

INSERT INTO municipalities (id, name, state, district, population, website)
VALUES ('amritsar_mc', 'Amritsar Municipal Corporation', 'Punjab', 'Amritsar', 1132761, NULL)
ON CONFLICT (id) DO UPDATE SET
    name = EXCLUDED.name,
    state = EXCLUDED.state,
    district = EXCLUDED.district,
    population = EXCLUDED.population,
    website = EXCLUDED.website;

INSERT INTO municipalities (id, name, state, district, population, website)
VALUES ('jalandhar_mc', 'Jalandhar Municipal Corporation', 'Punjab', 'Jalandhar', 862196, NULL)
ON CONFLICT (id) DO UPDATE SET
    name = EXCLUDED.name,
    state = EXCLUDED.state,
    district = EXCLUDED.district,
    population = EXCLUDED.population,
    website = EXCLUDED.website;

INSERT INTO municipalities (id, name, state, district, population, website)
VALUES ('patiala_mc', 'Patiala Municipal Corporation', 'Punjab', 'Patiala', 646800, NULL)
ON CONFLICT (id) DO UPDATE SET
    name = EXCLUDED.name,
    state = EXCLUDED.state,
    district = EXCLUDED.district,
    population = EXCLUDED.population,
    website = EXCLUDED.website;

INSERT INTO municipalities (id, name, state, district, population, website)
VALUES ('phagwara_mc', 'Phagwara Municipal Corporation', 'Punjab', 'Kapurthala', 117954, NULL)
ON CONFLICT (id) DO UPDATE SET
    name = EXCLUDED.name,
    state = EXCLUDED.state,
    district = EXCLUDED.district,
    population = EXCLUDED.population,
    website = EXCLUDED.website;

INSERT INTO municipalities (id, name, state, district, population, website)
VALUES ('bathinda_mc', 'Bathinda Municipal Corporation', 'Punjab', 'Bathinda', 285813, NULL)
ON CONFLICT (id) DO UPDATE SET
    name = EXCLUDED.name,
    state = EXCLUDED.state,
    district = EXCLUDED.district,
    population = EXCLUDED.population,
    website = EXCLUDED.website;

INSERT INTO municipalities (id, name, state, district, population, website)
VALUES ('batala_mc', 'Batala Municipal Corporation', 'Punjab', 'Gurdaspur', 211594, NULL)
ON CONFLICT (id) DO UPDATE SET
    name = EXCLUDED.name,
    state = EXCLUDED.state,
    district = EXCLUDED.district,
    population = EXCLUDED.population,
    website = EXCLUDED.website;

INSERT INTO municipalities (id, name, state, district, population, website)
VALUES ('mohali_mc', 'Mohali Municipal Corporation', 'Punjab', 'Mohali', 174000, NULL)
ON CONFLICT (id) DO UPDATE SET
    name = EXCLUDED.name,
    state = EXCLUDED.state,
    district = EXCLUDED.district,
    population = EXCLUDED.population,
    website = EXCLUDED.website;

INSERT INTO municipalities (id, name, state, district, population, website)
VALUES ('hoshiarpur_mc', 'Hoshiarpur Municipal Corporation', 'Punjab', 'Hoshiarpur', 168731, NULL)
ON CONFLICT (id) DO UPDATE SET
    name = EXCLUDED.name,
    state = EXCLUDED.state,
    district = EXCLUDED.district,
    population = EXCLUDED.population,
    website = EXCLUDED.website;

INSERT INTO municipalities (id, name, state, district, population, website)
VALUES ('moga_mc', 'Moga Municipal Corporation', 'Punjab', 'Moga', 163897, NULL)
ON CONFLICT (id) DO UPDATE SET
    name = EXCLUDED.name,
    state = EXCLUDED.state,
    district = EXCLUDED.district,
    population = EXCLUDED.population,
    website = EXCLUDED.website;

INSERT INTO municipalities (id, name, state, district, population, website)
VALUES ('pathankot_mc', 'Pathankot Municipal Corporation', 'Punjab', 'Pathankot', 159460, NULL)
ON CONFLICT (id) DO UPDATE SET
    name = EXCLUDED.name,
    state = EXCLUDED.state,
    district = EXCLUDED.district,
    population = EXCLUDED.population,
    website = EXCLUDED.website;

INSERT INTO municipalities (id, name, state, district, population, website)
VALUES ('abohar_mc', 'Abohar Municipal Corporation', 'Punjab', 'Fazilka', 145658, NULL)
ON CONFLICT (id) DO UPDATE SET
    name = EXCLUDED.name,
    state = EXCLUDED.state,
    district = EXCLUDED.district,
    population = EXCLUDED.population,
    website = EXCLUDED.website;

INSERT INTO municipalities (id, name, state, district, population, website)
VALUES ('kapurthala_mc', 'Kapurthala Municipal Corporation', 'Punjab', 'Kapurthala', 101854, NULL)
ON CONFLICT (id) DO UPDATE SET
    name = EXCLUDED.name,
    state = EXCLUDED.state,
    district = EXCLUDED.district,
    population = EXCLUDED.population,
    website = EXCLUDED.website;

INSERT INTO municipalities (id, name, state, district, population, website)
VALUES ('barnala_mc', 'Barnala Municipal Corporation', 'Punjab', 'Barnala', 285813, NULL)
ON CONFLICT (id) DO UPDATE SET
    name = EXCLUDED.name,
    state = EXCLUDED.state,
    district = EXCLUDED.district,
    population = EXCLUDED.population,
    website = EXCLUDED.website;

INSERT INTO municipalities (id, name, state, district, population, website)
VALUES ('ajmer_mc', 'Ajmer Municipal Corporation', 'Rajasthan', 'Ajmer', 542580, NULL)
ON CONFLICT (id) DO UPDATE SET
    name = EXCLUDED.name,
    state = EXCLUDED.state,
    district = EXCLUDED.district,
    population = EXCLUDED.population,
    website = EXCLUDED.website;

INSERT INTO municipalities (id, name, state, district, population, website)
VALUES ('alwar_mc', 'Alwar Municipal Corporation', 'Rajasthan', 'Alwar', 461618, NULL)
ON CONFLICT (id) DO UPDATE SET
    name = EXCLUDED.name,
    state = EXCLUDED.state,
    district = EXCLUDED.district,
    population = EXCLUDED.population,
    website = EXCLUDED.website;

INSERT INTO municipalities (id, name, state, district, population, website)
VALUES ('bharatpur_mc', 'Bharatpur Municipal Corporation', 'Rajasthan', 'Bharatpur', 252109, NULL)
ON CONFLICT (id) DO UPDATE SET
    name = EXCLUDED.name,
    state = EXCLUDED.state,
    district = EXCLUDED.district,
    population = EXCLUDED.population,
    website = EXCLUDED.website;

INSERT INTO municipalities (id, name, state, district, population, website)
VALUES ('bikaner_mc', 'Bikaner Municipal Corporation', 'Rajasthan', 'Bikaner', 647804, NULL)
ON CONFLICT (id) DO UPDATE SET
    name = EXCLUDED.name,
    state = EXCLUDED.state,
    district = EXCLUDED.district,
    population = EXCLUDED.population,
    website = EXCLUDED.website;

INSERT INTO municipalities (id, name, state, district, population, website)
VALUES ('bhilwara_mc', 'Bhilwara Municipal Corporation', 'Rajasthan', 'Bhilwara', 709483, NULL)
ON CONFLICT (id) DO UPDATE SET
    name = EXCLUDED.name,
    state = EXCLUDED.state,
    district = EXCLUDED.district,
    population = EXCLUDED.population,
    website = EXCLUDED.website;

INSERT INTO municipalities (id, name, state, district, population, website)
VALUES ('jaipur_mc', 'Jaipur Municipal Corporation', 'Rajasthan', 'Jaipur', 3073350, NULL)
ON CONFLICT (id) DO UPDATE SET
    name = EXCLUDED.name,
    state = EXCLUDED.state,
    district = EXCLUDED.district,
    population = EXCLUDED.population,
    website = EXCLUDED.website;

INSERT INTO municipalities (id, name, state, district, population, website)
VALUES ('jodhpur_mc', 'Jodhpur Municipal Corporation', 'Rajasthan', 'Jodhpur', 1033756, NULL)
ON CONFLICT (id) DO UPDATE SET
    name = EXCLUDED.name,
    state = EXCLUDED.state,
    district = EXCLUDED.district,
    population = EXCLUDED.population,
    website = EXCLUDED.website;

INSERT INTO municipalities (id, name, state, district, population, website)
VALUES ('kota_mc', 'Kota Municipal Corporation', 'Rajasthan', 'Kota', 1001365, NULL)
ON CONFLICT (id) DO UPDATE SET
    name = EXCLUDED.name,
    state = EXCLUDED.state,
    district = EXCLUDED.district,
    population = EXCLUDED.population,
    website = EXCLUDED.website;

INSERT INTO municipalities (id, name, state, district, population, website)
VALUES ('udaipur_mc', 'Udaipur Municipal Corporation', 'Rajasthan', 'Udaipur', 451735, NULL)
ON CONFLICT (id) DO UPDATE SET
    name = EXCLUDED.name,
    state = EXCLUDED.state,
    district = EXCLUDED.district,
    population = EXCLUDED.population,
    website = EXCLUDED.website;

INSERT INTO municipalities (id, name, state, district, population, website)
VALUES ('gangtok_mc', 'Gangtok Municipal Corporation', 'Sikkim', 'East Sikkim', 98658, NULL)
ON CONFLICT (id) DO UPDATE SET
    name = EXCLUDED.name,
    state = EXCLUDED.state,
    district = EXCLUDED.district,
    population = EXCLUDED.population,
    website = EXCLUDED.website;

INSERT INTO municipalities (id, name, state, district, population, website)
VALUES ('chennai_mc', 'Greater Chennai Corporation', 'Tamil Nadu', 'Chennai', 7139630, NULL)
ON CONFLICT (id) DO UPDATE SET
    name = EXCLUDED.name,
    state = EXCLUDED.state,
    district = EXCLUDED.district,
    population = EXCLUDED.population,
    website = EXCLUDED.website;

INSERT INTO municipalities (id, name, state, district, population, website)
VALUES ('madurai_mc', 'Madurai Municipal Corporation', 'Tamil Nadu', 'Madurai', 1638252, NULL)
ON CONFLICT (id) DO UPDATE SET
    name = EXCLUDED.name,
    state = EXCLUDED.state,
    district = EXCLUDED.district,
    population = EXCLUDED.population,
    website = EXCLUDED.website;

INSERT INTO municipalities (id, name, state, district, population, website)
VALUES ('coimbatore_mc', 'Coimbatore Municipal Corporation', 'Tamil Nadu', 'Coimbatore', 1758025, NULL)
ON CONFLICT (id) DO UPDATE SET
    name = EXCLUDED.name,
    state = EXCLUDED.state,
    district = EXCLUDED.district,
    population = EXCLUDED.population,
    website = EXCLUDED.website;

INSERT INTO municipalities (id, name, state, district, population, website)
VALUES ('tiruchirappalli_mc', 'Tiruchirappalli City Municipal Corporation', 'Tamil Nadu', 'Tiruchirappalli', 1122717, NULL)
ON CONFLICT (id) DO UPDATE SET
    name = EXCLUDED.name,
    state = EXCLUDED.state,
    district = EXCLUDED.district,
    population = EXCLUDED.population,
    website = EXCLUDED.website;

INSERT INTO municipalities (id, name, state, district, population, website)
VALUES ('salem_mc', 'Salem City Municipal Corporation', 'Tamil Nadu', 'Salem', 932336, NULL)
ON CONFLICT (id) DO UPDATE SET
    name = EXCLUDED.name,
    state = EXCLUDED.state,
    district = EXCLUDED.district,
    population = EXCLUDED.population,
    website = EXCLUDED.website;

INSERT INTO municipalities (id, name, state, district, population, website)
VALUES ('tirunelveli_mc', 'Tirunelveli Municipal Corporation', 'Tamil Nadu', 'Tirunelveli', 868874, NULL)
ON CONFLICT (id) DO UPDATE SET
    name = EXCLUDED.name,
    state = EXCLUDED.state,
    district = EXCLUDED.district,
    population = EXCLUDED.population,
    website = EXCLUDED.website;

INSERT INTO municipalities (id, name, state, district, population, website)
VALUES ('tiruppur_mc', 'Tiruppur City Municipal Corporation', 'Tamil Nadu', 'Tiruppur', 963150, NULL)
ON CONFLICT (id) DO UPDATE SET
    name = EXCLUDED.name,
    state = EXCLUDED.state,
    district = EXCLUDED.district,
    population = EXCLUDED.population,
    website = EXCLUDED.website;

INSERT INTO municipalities (id, name, state, district, population, website)
VALUES ('erode_mc', 'Erode City Municipal Corporation', 'Tamil Nadu', 'Erode', 521776, NULL)
ON CONFLICT (id) DO UPDATE SET
    name = EXCLUDED.name,
    state = EXCLUDED.state,
    district = EXCLUDED.district,
    population = EXCLUDED.population,
    website = EXCLUDED.website;

INSERT INTO municipalities (id, name, state, district, population, website)
VALUES ('vellore_mc', 'Vellore Municipal Corporation', 'Tamil Nadu', 'Vellore', 687981, NULL)
ON CONFLICT (id) DO UPDATE SET
    name = EXCLUDED.name,
    state = EXCLUDED.state,
    district = EXCLUDED.district,
    population = EXCLUDED.population,
    website = EXCLUDED.website;

INSERT INTO municipalities (id, name, state, district, population, website)
VALUES ('thoothukudi_mc', 'Thoothukkudi City Municipal Corporation', 'Tamil Nadu', 'Thoothukudi', 431628, NULL)
ON CONFLICT (id) DO UPDATE SET
    name = EXCLUDED.name,
    state = EXCLUDED.state,
    district = EXCLUDED.district,
    population = EXCLUDED.population,
    website = EXCLUDED.website;

INSERT INTO municipalities (id, name, state, district, population, website)
VALUES ('dindigul_mc', 'Dindigul Municipal Corporation', 'Tamil Nadu', 'Dindigul', 268643, NULL)
ON CONFLICT (id) DO UPDATE SET
    name = EXCLUDED.name,
    state = EXCLUDED.state,
    district = EXCLUDED.district,
    population = EXCLUDED.population,
    website = EXCLUDED.website;

INSERT INTO municipalities (id, name, state, district, population, website)
VALUES ('thanjavur_mc', 'Thanjavur Municipal Corporation', 'Tamil Nadu', 'Thanjavur', 322236, NULL)
ON CONFLICT (id) DO UPDATE SET
    name = EXCLUDED.name,
    state = EXCLUDED.state,
    district = EXCLUDED.district,
    population = EXCLUDED.population,
    website = EXCLUDED.website;

INSERT INTO municipalities (id, name, state, district, population, website)
VALUES ('nagercoil_mc', 'Nagercoil Municipal Corporation', 'Tamil Nadu', 'Kanyakumari', 236774, NULL)
ON CONFLICT (id) DO UPDATE SET
    name = EXCLUDED.name,
    state = EXCLUDED.state,
    district = EXCLUDED.district,
    population = EXCLUDED.population,
    website = EXCLUDED.website;

INSERT INTO municipalities (id, name, state, district, population, website)
VALUES ('hosur_mc', 'Hosur Municipal Corporation', 'Tamil Nadu', 'Krishnagiri', 245354, NULL)
ON CONFLICT (id) DO UPDATE SET
    name = EXCLUDED.name,
    state = EXCLUDED.state,
    district = EXCLUDED.district,
    population = EXCLUDED.population,
    website = EXCLUDED.website;

INSERT INTO municipalities (id, name, state, district, population, website)
VALUES ('kumbakonam_mc', 'Kumbakonam Municipal Corporation', 'Tamil Nadu', 'Thanjavur', 223763, NULL)
ON CONFLICT (id) DO UPDATE SET
    name = EXCLUDED.name,
    state = EXCLUDED.state,
    district = EXCLUDED.district,
    population = EXCLUDED.population,
    website = EXCLUDED.website;

INSERT INTO municipalities (id, name, state, district, population, website)
VALUES ('avadi_mc', 'Avadi Municipal Corporation', 'Tamil Nadu', 'Thiruvallur', 612446, NULL)
ON CONFLICT (id) DO UPDATE SET
    name = EXCLUDED.name,
    state = EXCLUDED.state,
    district = EXCLUDED.district,
    population = EXCLUDED.population,
    website = EXCLUDED.website;

INSERT INTO municipalities (id, name, state, district, population, website)
VALUES ('tambaram_mc', 'Tambaram Corporation', 'Tamil Nadu', 'Chengalpattu', 1096591, NULL)
ON CONFLICT (id) DO UPDATE SET
    name = EXCLUDED.name,
    state = EXCLUDED.state,
    district = EXCLUDED.district,
    population = EXCLUDED.population,
    website = EXCLUDED.website;

INSERT INTO municipalities (id, name, state, district, population, website)
VALUES ('kancheepuram_mc', 'Kancheepuram Municipal Corporation', 'Tamil Nadu', 'Kanchipuram', 311598, NULL)
ON CONFLICT (id) DO UPDATE SET
    name = EXCLUDED.name,
    state = EXCLUDED.state,
    district = EXCLUDED.district,
    population = EXCLUDED.population,
    website = EXCLUDED.website;

INSERT INTO municipalities (id, name, state, district, population, website)
VALUES ('karur_mc', 'Karur Municipal corporation', 'Tamil Nadu', 'Karur', 358468, NULL)
ON CONFLICT (id) DO UPDATE SET
    name = EXCLUDED.name,
    state = EXCLUDED.state,
    district = EXCLUDED.district,
    population = EXCLUDED.population,
    website = EXCLUDED.website;

INSERT INTO municipalities (id, name, state, district, population, website)
VALUES ('cuddalore_mc', 'Cuddalore Municipal corporation', 'Tamil Nadu', 'Cuddalore', 173639, NULL)
ON CONFLICT (id) DO UPDATE SET
    name = EXCLUDED.name,
    state = EXCLUDED.state,
    district = EXCLUDED.district,
    population = EXCLUDED.population,
    website = EXCLUDED.website;

INSERT INTO municipalities (id, name, state, district, population, website)
VALUES ('sivakasi_mc', 'Sivakasi Municipal corporation', 'Tamil Nadu', 'Virudhunagar', 260047, NULL)
ON CONFLICT (id) DO UPDATE SET
    name = EXCLUDED.name,
    state = EXCLUDED.state,
    district = EXCLUDED.district,
    population = EXCLUDED.population,
    website = EXCLUDED.website;

INSERT INTO municipalities (id, name, state, district, population, website)
VALUES ('karaikudi_mc', 'Karaikudi Municipal Corporation', 'Tamil Nadu', 'Sivaganga', 303291, NULL)
ON CONFLICT (id) DO UPDATE SET
    name = EXCLUDED.name,
    state = EXCLUDED.state,
    district = EXCLUDED.district,
    population = EXCLUDED.population,
    website = EXCLUDED.website;

INSERT INTO municipalities (id, name, state, district, population, website)
VALUES ('namakkal_mc', 'Namakkal Municipal Corporation', 'Tamil Nadu', 'Namakkal', NULL, NULL)
ON CONFLICT (id) DO UPDATE SET
    name = EXCLUDED.name,
    state = EXCLUDED.state,
    district = EXCLUDED.district,
    population = EXCLUDED.population,
    website = EXCLUDED.website;

INSERT INTO municipalities (id, name, state, district, population, website)
VALUES ('pudukkottai_mc', 'Pudukottai Municipal Corporation', 'Tamil Nadu', 'Pudukkottai', NULL, NULL)
ON CONFLICT (id) DO UPDATE SET
    name = EXCLUDED.name,
    state = EXCLUDED.state,
    district = EXCLUDED.district,
    population = EXCLUDED.population,
    website = EXCLUDED.website;

INSERT INTO municipalities (id, name, state, district, population, website)
VALUES ('tiruvannamalai_mc', 'Tiruvannamalai Municipal Corporation', 'Tamil Nadu', 'Tiruvannamalai', NULL, NULL)
ON CONFLICT (id) DO UPDATE SET
    name = EXCLUDED.name,
    state = EXCLUDED.state,
    district = EXCLUDED.district,
    population = EXCLUDED.population,
    website = EXCLUDED.website;

INSERT INTO municipalities (id, name, state, district, population, website)
VALUES ('hyderabad_mc', 'Greater Hyderabad Municipal Corporation', 'Telangana', 'Hyderabad, Ranga Reddy, Medchal–Malkajgiri and Sangareddy', 7677018, NULL)
ON CONFLICT (id) DO UPDATE SET
    name = EXCLUDED.name,
    state = EXCLUDED.state,
    district = EXCLUDED.district,
    population = EXCLUDED.population,
    website = EXCLUDED.website;

INSERT INTO municipalities (id, name, state, district, population, website)
VALUES ('warangal_mc', 'Greater Warangal Municipal Corporation', 'Telangana', 'Warangal', 1020116, NULL)
ON CONFLICT (id) DO UPDATE SET
    name = EXCLUDED.name,
    state = EXCLUDED.state,
    district = EXCLUDED.district,
    population = EXCLUDED.population,
    website = EXCLUDED.website;

INSERT INTO municipalities (id, name, state, district, population, website)
VALUES ('karimnagar_mc', 'Karimnagar Municipal Corporation', 'Telangana', 'Karimnagar', 261185, NULL)
ON CONFLICT (id) DO UPDATE SET
    name = EXCLUDED.name,
    state = EXCLUDED.state,
    district = EXCLUDED.district,
    population = EXCLUDED.population,
    website = EXCLUDED.website;

INSERT INTO municipalities (id, name, state, district, population, website)
VALUES ('nizamabad_mc', 'Nizamabad Municipal Corporation', 'Telangana', 'Nizamabad', 311467, NULL)
ON CONFLICT (id) DO UPDATE SET
    name = EXCLUDED.name,
    state = EXCLUDED.state,
    district = EXCLUDED.district,
    population = EXCLUDED.population,
    website = EXCLUDED.website;

INSERT INTO municipalities (id, name, state, district, population, website)
VALUES ('ramagundam_mc', 'Ramagundam Municipal Corporation', 'Telangana', 'Peddapalli', 229644, NULL)
ON CONFLICT (id) DO UPDATE SET
    name = EXCLUDED.name,
    state = EXCLUDED.state,
    district = EXCLUDED.district,
    population = EXCLUDED.population,
    website = EXCLUDED.website;

INSERT INTO municipalities (id, name, state, district, population, website)
VALUES ('khammam_mc', 'Khammam Municipal Corporation', 'Telangana', 'Khammam', 305000, NULL)
ON CONFLICT (id) DO UPDATE SET
    name = EXCLUDED.name,
    state = EXCLUDED.state,
    district = EXCLUDED.district,
    population = EXCLUDED.population,
    website = EXCLUDED.website;

INSERT INTO municipalities (id, name, state, district, population, website)
VALUES ('mancherial_mc', 'Mancherial Municipal Corporation', 'Telangana', 'Mancherial', 174618, NULL)
ON CONFLICT (id) DO UPDATE SET
    name = EXCLUDED.name,
    state = EXCLUDED.state,
    district = EXCLUDED.district,
    population = EXCLUDED.population,
    website = EXCLUDED.website;

INSERT INTO municipalities (id, name, state, district, population, website)
VALUES ('mahabubnagar_mc', 'Mahabubnagar Municipal Corporation', 'Telangana', 'Mahabubnagar', 222573, NULL)
ON CONFLICT (id) DO UPDATE SET
    name = EXCLUDED.name,
    state = EXCLUDED.state,
    district = EXCLUDED.district,
    population = EXCLUDED.population,
    website = EXCLUDED.website;

INSERT INTO municipalities (id, name, state, district, population, website)
VALUES ('kothagudem_mc', 'Kothagudem Municipal Corporation', 'Telangana', 'Bhadradri Kothagudem', NULL, NULL)
ON CONFLICT (id) DO UPDATE SET
    name = EXCLUDED.name,
    state = EXCLUDED.state,
    district = EXCLUDED.district,
    population = EXCLUDED.population,
    website = EXCLUDED.website;

INSERT INTO municipalities (id, name, state, district, population, website)
VALUES ('nalgonda_mc', 'Nalgonda Municipal Corporation', 'Telangana', 'Nalgonda', NULL, NULL)
ON CONFLICT (id) DO UPDATE SET
    name = EXCLUDED.name,
    state = EXCLUDED.state,
    district = EXCLUDED.district,
    population = EXCLUDED.population,
    website = EXCLUDED.website;

INSERT INTO municipalities (id, name, state, district, population, website)
VALUES ('agartala_mc', 'Agartala Municipal Corporation', 'Tripura', 'West Tripura', 450000, NULL)
ON CONFLICT (id) DO UPDATE SET
    name = EXCLUDED.name,
    state = EXCLUDED.state,
    district = EXCLUDED.district,
    population = EXCLUDED.population,
    website = EXCLUDED.website;

INSERT INTO municipalities (id, name, state, district, population, website)
VALUES ('lucknow_mc', 'Lucknow Municipal Corporation', 'Uttar Pradesh', 'Lucknow', 2815601, NULL)
ON CONFLICT (id) DO UPDATE SET
    name = EXCLUDED.name,
    state = EXCLUDED.state,
    district = EXCLUDED.district,
    population = EXCLUDED.population,
    website = EXCLUDED.website;

INSERT INTO municipalities (id, name, state, district, population, website)
VALUES ('kanpur_mc', 'Kanpur Municipal Corporation', 'Uttar Pradesh', 'Kanpur Nagar', 2767031, NULL)
ON CONFLICT (id) DO UPDATE SET
    name = EXCLUDED.name,
    state = EXCLUDED.state,
    district = EXCLUDED.district,
    population = EXCLUDED.population,
    website = EXCLUDED.website;

INSERT INTO municipalities (id, name, state, district, population, website)
VALUES ('agra_mc', 'Agra Municipal Corporation', 'Uttar Pradesh', 'Agra', 2470996, NULL)
ON CONFLICT (id) DO UPDATE SET
    name = EXCLUDED.name,
    state = EXCLUDED.state,
    district = EXCLUDED.district,
    population = EXCLUDED.population,
    website = EXCLUDED.website;

INSERT INTO municipalities (id, name, state, district, population, website)
VALUES ('ghaziabad_mc', 'Ghaziabad Municipal Corporation', 'Uttar Pradesh', 'Ghaziabad', 2458525, NULL)
ON CONFLICT (id) DO UPDATE SET
    name = EXCLUDED.name,
    state = EXCLUDED.state,
    district = EXCLUDED.district,
    population = EXCLUDED.population,
    website = EXCLUDED.website;

INSERT INTO municipalities (id, name, state, district, population, website)
VALUES ('varanasi_mc', 'Varanasi Municipal Corporation', 'Uttar Pradesh', 'Varanasi', 1746467, NULL)
ON CONFLICT (id) DO UPDATE SET
    name = EXCLUDED.name,
    state = EXCLUDED.state,
    district = EXCLUDED.district,
    population = EXCLUDED.population,
    website = EXCLUDED.website;

INSERT INTO municipalities (id, name, state, district, population, website)
VALUES ('meerut_mc', 'Meerut Municipal Corporation', 'Uttar Pradesh', 'Meerut', 1435113, NULL)
ON CONFLICT (id) DO UPDATE SET
    name = EXCLUDED.name,
    state = EXCLUDED.state,
    district = EXCLUDED.district,
    population = EXCLUDED.population,
    website = EXCLUDED.website;

INSERT INTO municipalities (id, name, state, district, population, website)
VALUES ('prayagraj_mc', 'Prayagraj Municipal Corporation', 'Uttar Pradesh', 'Prayagraj', 1424908, NULL)
ON CONFLICT (id) DO UPDATE SET
    name = EXCLUDED.name,
    state = EXCLUDED.state,
    district = EXCLUDED.district,
    population = EXCLUDED.population,
    website = EXCLUDED.website;

INSERT INTO municipalities (id, name, state, district, population, website)
VALUES ('aligarh_mc', 'Aligarh Municipal Corporation', 'Uttar Pradesh', 'Aligarh', 1216719, NULL)
ON CONFLICT (id) DO UPDATE SET
    name = EXCLUDED.name,
    state = EXCLUDED.state,
    district = EXCLUDED.district,
    population = EXCLUDED.population,
    website = EXCLUDED.website;

INSERT INTO municipalities (id, name, state, district, population, website)
VALUES ('bareilly_mc', 'Bareilly Municipal Corporation', 'Uttar Pradesh', 'Bareilly', 959933, NULL)
ON CONFLICT (id) DO UPDATE SET
    name = EXCLUDED.name,
    state = EXCLUDED.state,
    district = EXCLUDED.district,
    population = EXCLUDED.population,
    website = EXCLUDED.website;

INSERT INTO municipalities (id, name, state, district, population, website)
VALUES ('ayodhya_mc', 'Ayodhya Municipal Corporation', 'Uttar Pradesh', 'Ayodhya', 909559, NULL)
ON CONFLICT (id) DO UPDATE SET
    name = EXCLUDED.name,
    state = EXCLUDED.state,
    district = EXCLUDED.district,
    population = EXCLUDED.population,
    website = EXCLUDED.website;

INSERT INTO municipalities (id, name, state, district, population, website)
VALUES ('moradabad_mc', 'Moradabad Municipal Corporation', 'Uttar Pradesh', 'Moradabad', 889810, NULL)
ON CONFLICT (id) DO UPDATE SET
    name = EXCLUDED.name,
    state = EXCLUDED.state,
    district = EXCLUDED.district,
    population = EXCLUDED.population,
    website = EXCLUDED.website;

INSERT INTO municipalities (id, name, state, district, population, website)
VALUES ('saharanpur_mc', 'Saharanpur Municipal Corporation', 'Uttar Pradesh', 'Saharanpur', 703345, NULL)
ON CONFLICT (id) DO UPDATE SET
    name = EXCLUDED.name,
    state = EXCLUDED.state,
    district = EXCLUDED.district,
    population = EXCLUDED.population,
    website = EXCLUDED.website;

INSERT INTO municipalities (id, name, state, district, population, website)
VALUES ('gorakhpur_mc', 'Gorakhpur Municipal Corporation', 'Uttar Pradesh', 'Gorakhpur', 1500000, NULL)
ON CONFLICT (id) DO UPDATE SET
    name = EXCLUDED.name,
    state = EXCLUDED.state,
    district = EXCLUDED.district,
    population = EXCLUDED.population,
    website = EXCLUDED.website;

INSERT INTO municipalities (id, name, state, district, population, website)
VALUES ('firozabad_mc', 'Firozabad Municipal Corporation', 'Uttar Pradesh', 'Firozabad', 603797, NULL)
ON CONFLICT (id) DO UPDATE SET
    name = EXCLUDED.name,
    state = EXCLUDED.state,
    district = EXCLUDED.district,
    population = EXCLUDED.population,
    website = EXCLUDED.website;

INSERT INTO municipalities (id, name, state, district, population, website)
VALUES ('mathura__vrindavan_mc', 'Mathura - Vrindavan Municipal Corporation', 'Uttar Pradesh', 'Mathura', 602897, NULL)
ON CONFLICT (id) DO UPDATE SET
    name = EXCLUDED.name,
    state = EXCLUDED.state,
    district = EXCLUDED.district,
    population = EXCLUDED.population,
    website = EXCLUDED.website;

INSERT INTO municipalities (id, name, state, district, population, website)
VALUES ('jhansi_mc', 'Jhansi Municipal Corporation', 'Uttar Pradesh', 'Jhansi', 592899, NULL)
ON CONFLICT (id) DO UPDATE SET
    name = EXCLUDED.name,
    state = EXCLUDED.state,
    district = EXCLUDED.district,
    population = EXCLUDED.population,
    website = EXCLUDED.website;

INSERT INTO municipalities (id, name, state, district, population, website)
VALUES ('shahjahanpur_mc', 'Shahjahanpur Municipal Corporation', 'Uttar Pradesh', 'Shahjahanpur', 346103, NULL)
ON CONFLICT (id) DO UPDATE SET
    name = EXCLUDED.name,
    state = EXCLUDED.state,
    district = EXCLUDED.district,
    population = EXCLUDED.population,
    website = EXCLUDED.website;

INSERT INTO municipalities (id, name, state, district, population, website)
VALUES ('almora_mc', 'Almora Municipal Corporation', 'Uttarakhand', 'Almora', 39600, NULL)
ON CONFLICT (id) DO UPDATE SET
    name = EXCLUDED.name,
    state = EXCLUDED.state,
    district = EXCLUDED.district,
    population = EXCLUDED.population,
    website = EXCLUDED.website;

INSERT INTO municipalities (id, name, state, district, population, website)
VALUES ('dehradun_mc', 'Dehradun Municipal Corporation', 'Uttarakhand', 'Dehradun', 578420, NULL)
ON CONFLICT (id) DO UPDATE SET
    name = EXCLUDED.name,
    state = EXCLUDED.state,
    district = EXCLUDED.district,
    population = EXCLUDED.population,
    website = EXCLUDED.website;

INSERT INTO municipalities (id, name, state, district, population, website)
VALUES ('haldwani_mc', 'Haldwani Municipal Corporation', 'Uttarakhand', 'Nainital', 225235, NULL)
ON CONFLICT (id) DO UPDATE SET
    name = EXCLUDED.name,
    state = EXCLUDED.state,
    district = EXCLUDED.district,
    population = EXCLUDED.population,
    website = EXCLUDED.website;

INSERT INTO municipalities (id, name, state, district, population, website)
VALUES ('haridwar_mc', 'Haridwar Municipal Corporation', 'Uttarakhand', 'Haridwar', 156060, NULL)
ON CONFLICT (id) DO UPDATE SET
    name = EXCLUDED.name,
    state = EXCLUDED.state,
    district = EXCLUDED.district,
    population = EXCLUDED.population,
    website = EXCLUDED.website;

INSERT INTO municipalities (id, name, state, district, population, website)
VALUES ('kashipur_mc', 'Kashipur Municipal Corporation', 'Uttarakhand', 'Udham Singh Nagar', 121610, NULL)
ON CONFLICT (id) DO UPDATE SET
    name = EXCLUDED.name,
    state = EXCLUDED.state,
    district = EXCLUDED.district,
    population = EXCLUDED.population,
    website = EXCLUDED.website;

INSERT INTO municipalities (id, name, state, district, population, website)
VALUES ('kotdwar_mc', 'Kotdwar Municipal Corporation', 'Uttarakhand', 'Pauri Garhwal', 28859, NULL)
ON CONFLICT (id) DO UPDATE SET
    name = EXCLUDED.name,
    state = EXCLUDED.state,
    district = EXCLUDED.district,
    population = EXCLUDED.population,
    website = EXCLUDED.website;

INSERT INTO municipalities (id, name, state, district, population, website)
VALUES ('pithoragarh_mc', 'Pithoragarh Municipal Corporation', 'Uttarakhand', 'Pithoragarh', 62500, NULL)
ON CONFLICT (id) DO UPDATE SET
    name = EXCLUDED.name,
    state = EXCLUDED.state,
    district = EXCLUDED.district,
    population = EXCLUDED.population,
    website = EXCLUDED.website;

INSERT INTO municipalities (id, name, state, district, population, website)
VALUES ('rishikesh_mc', 'Rishikesh Municipal Corporation', 'Uttarakhand', 'Dehradun', 104249, NULL)
ON CONFLICT (id) DO UPDATE SET
    name = EXCLUDED.name,
    state = EXCLUDED.state,
    district = EXCLUDED.district,
    population = EXCLUDED.population,
    website = EXCLUDED.website;

INSERT INTO municipalities (id, name, state, district, population, website)
VALUES ('roorkee_mc', 'Roorkee Municipal Corporation', 'Uttarakhand', 'Haridwar', 118188, NULL)
ON CONFLICT (id) DO UPDATE SET
    name = EXCLUDED.name,
    state = EXCLUDED.state,
    district = EXCLUDED.district,
    population = EXCLUDED.population,
    website = EXCLUDED.website;

INSERT INTO municipalities (id, name, state, district, population, website)
VALUES ('rudrapur_mc', 'Rudrapur Municipal Corporation', 'Uttarakhand', 'Udham Singh Nagar', 140884, NULL)
ON CONFLICT (id) DO UPDATE SET
    name = EXCLUDED.name,
    state = EXCLUDED.state,
    district = EXCLUDED.district,
    population = EXCLUDED.population,
    website = EXCLUDED.website;

INSERT INTO municipalities (id, name, state, district, population, website)
VALUES ('srinagar_mc', 'Srinagar Municipal Corporation', 'Uttarakhand', 'Pauri Garhwal', 37911, NULL)
ON CONFLICT (id) DO UPDATE SET
    name = EXCLUDED.name,
    state = EXCLUDED.state,
    district = EXCLUDED.district,
    population = EXCLUDED.population,
    website = EXCLUDED.website;

INSERT INTO municipalities (id, name, state, district, population, website)
VALUES ('asansol_mc', 'Asansol Municipal Corporation', 'West Bengal', 'Paschim Bardhaman', 1153138, NULL)
ON CONFLICT (id) DO UPDATE SET
    name = EXCLUDED.name,
    state = EXCLUDED.state,
    district = EXCLUDED.district,
    population = EXCLUDED.population,
    website = EXCLUDED.website;

INSERT INTO municipalities (id, name, state, district, population, website)
VALUES ('bidhannagar_mc', 'Bidhannagar Municipal Corporation', 'West Bengal', 'North 24 Parganas', 632107, NULL)
ON CONFLICT (id) DO UPDATE SET
    name = EXCLUDED.name,
    state = EXCLUDED.state,
    district = EXCLUDED.district,
    population = EXCLUDED.population,
    website = EXCLUDED.website;

INSERT INTO municipalities (id, name, state, district, population, website)
VALUES ('chandannagar_mc', 'Chandernagore Municipal Corporation', 'West Bengal', 'Hooghly', 166761, NULL)
ON CONFLICT (id) DO UPDATE SET
    name = EXCLUDED.name,
    state = EXCLUDED.state,
    district = EXCLUDED.district,
    population = EXCLUDED.population,
    website = EXCLUDED.website;

INSERT INTO municipalities (id, name, state, district, population, website)
VALUES ('durgapur_mc', 'Durgapur Municipal Corporation', 'West Bengal', 'Paschim Bardhaman', 566517, NULL)
ON CONFLICT (id) DO UPDATE SET
    name = EXCLUDED.name,
    state = EXCLUDED.state,
    district = EXCLUDED.district,
    population = EXCLUDED.population,
    website = EXCLUDED.website;

INSERT INTO municipalities (id, name, state, district, population, website)
VALUES ('howrah_mc', 'Howrah Municipal Corporation', 'West Bengal', 'Howrah', 1370448, NULL)
ON CONFLICT (id) DO UPDATE SET
    name = EXCLUDED.name,
    state = EXCLUDED.state,
    district = EXCLUDED.district,
    population = EXCLUDED.population,
    website = EXCLUDED.website;

INSERT INTO municipalities (id, name, state, district, population, website)
VALUES ('kolkata_mc', 'Kolkata Municipal Corporation', 'West Bengal', 'Kolkata', 4496694, NULL)
ON CONFLICT (id) DO UPDATE SET
    name = EXCLUDED.name,
    state = EXCLUDED.state,
    district = EXCLUDED.district,
    population = EXCLUDED.population,
    website = EXCLUDED.website;

INSERT INTO municipalities (id, name, state, district, population, website)
VALUES ('siliguri_mc', 'Siliguri Municipal Corporation', 'West Bengal', 'Darjeeling and Jalpaiguri', 513264, NULL)
ON CONFLICT (id) DO UPDATE SET
    name = EXCLUDED.name,
    state = EXCLUDED.state,
    district = EXCLUDED.district,
    population = EXCLUDED.population,
    website = EXCLUDED.website;

INSERT INTO municipalities (id, name, state, district, population, website)
VALUES ('chandigarh_mc', 'Chandigarh Municipal Corporation', 'Chandigarh', 'Chandigarh', 960787, NULL)
ON CONFLICT (id) DO UPDATE SET
    name = EXCLUDED.name,
    state = EXCLUDED.state,
    district = EXCLUDED.district,
    population = EXCLUDED.population,
    website = EXCLUDED.website;

INSERT INTO municipalities (id, name, state, district, population, website)
VALUES ('delhi_mc', 'Municipal Corporation of Delhi', 'Delhi', 'Delhi', NULL, NULL)
ON CONFLICT (id) DO UPDATE SET
    name = EXCLUDED.name,
    state = EXCLUDED.state,
    district = EXCLUDED.district,
    population = EXCLUDED.population,
    website = EXCLUDED.website;

INSERT INTO municipalities (id, name, state, district, population, website)
VALUES ('jammu_mc', 'Jammu Municipal Corporation', 'Jammu and Kashmir', 'Jammu', 951373, NULL)
ON CONFLICT (id) DO UPDATE SET
    name = EXCLUDED.name,
    state = EXCLUDED.state,
    district = EXCLUDED.district,
    population = EXCLUDED.population,
    website = EXCLUDED.website;
